label cap4_1:

    "Mais um dia."
    #inicio das atividades do dia
    
    "Encontro Nádia na cozinha."
    n "Finalmente acordou no horário, Moon?"
    m "*bocejo* Bom dia, pra você também..."
    n "Garota... 'cê tá acabada, hein."
    m "Ah, isso é normal..."
    m "Queria ter a habilidade de acordar disposta todos os dias."
    m "Como a Linne... "
    m "Aliás, cadê ela?"
    n "Uh, sei lá."
    n "Talvez treinando?"
    m "M-mas já?"
    m "Ainda é muito cedo..."
    m "Você não acha isso preocupante?"
    n "Um pouquinho... mas, tipo, eu vou fazer o quê?"
    n "A doida não gosta que a gente questione ela."
    m "..."
    "Treinando? Mal amanheceu..."
    n "..."
    n "B-bem... Tô indo nessa, Moon."
    n "Até mais tar..."
    "Será que ela está bem? Devo falar com ela?"
    "Mas a Nádia disse que ela não gosta..."
    "Independentemente... todos precisamos de ajuda de vez em quando."
    "É isso! Vou falar com ela."
    m "Acho que vou-"
    m "Hã?"
    "Notei que Nádia já não estava mais lá."
    "Quando ela saiu? Nem tinha percebido..."
    "Bom, vou tomar meu café... e aí vou procurar por ela."
    "Será que ela está na academia? ou na-"
    l "Moon?"
    m "Ah, bom dia, Linne."
    "Ela pode estar no studio-"
    m "Espera... Você está aqui!"
    l "Hm. Sim, estou aqui."
    "Seu rosto está inchado e ela parece sonolenta."
    #"Será que... ela acordou agora? Isso é possível?"
    m "Acordou agora, Linne?"
    l "..."
    "Ela fica irritada pela pergunta."
    m "Oh, d-desculpa! Eu não queria..."
    m "S-sabe, é que isso não é tão comum."
    m "Acho que a gente trocou de lugar hoje. He he..."
    m "Já que você perdeu o horário..."
    l "..."
    m "..."
    l "Não estou com muita vontade de conversar hoje."
    "Ela simplesmente dá meia volta e sai."
    "Com certeza tem algo errado."
    "E o pior... ela não está aberta a conversar agora."
    "Bem que Nádia tentou avisar..."
    "Mas eu só queria poder ajudar."
    "... Mas, tenho que começar a treinar. Não posso dar mole, mesmo com minhas   *******."
    
    "Mais tarde eu converso com ela."
    # Treinamento

    "Começo o dia treinando cardio."
    "E logo após, treinei meu canto."
    "Só que... não conseguia parar de pensar sobre o que aconteceu hoje mais cedo."

    # hr do Almoco
label cap4_2:
    "Me encontrei com Nádia para almoçarmos."
    n "Finalmente! Tô morta de fome."
    "Será que eu consigo convencer Nádia a conversar com Linne?"
    "Ah, já sei!"
    m "Uh, Nádia..."
    m "Você e Linne eram amigas, não?"
    n "Ah-hã. Porque?"
    m "Bem..."
    n "Pera. Eu já sei o que cê vai falar."
    n "'Ain, você poderia falar com ela pipipi pópópó'"
    m "C-como sabe?!"
    n "Imaginei."
    m "E então... o que acha?"
    n "..."
    n "Não sei, não..."
    m "O que? Porque?"
    m "Sabe, não custa nada-"
    n "Vem cá. Eu vou te contar uma coisa."
    n "Quando eramos pequenas, nossas famílias eram bem próximas."
    n "Na família dela, a arte era super incentivada."
    n "Um negócio meio tradicional, sabe?"
    n "E eles sempre frequentavam nosso restaurante... e nós duas eramos praticamente inseparaveis."
    #n "A gente ia e voltava da escola juntas... dormia na casa uma da outra..."
    n "E tipo, conforme fomos crescendo, as coisas foram mudando."
    n "Minha família começou a passar por problemas financeiros."
    n "Mas a dela estava enriquecendo por conta da carreira artística bem sucedida de alguns parentes."
    n "Assim, eles pararam de frequentar o restaurante."
    n "O que não nos impediu de continuarmos amigas por um tempo."
    n "Ela me levava pra algumas aulas de canto e dança com ela."
    n "Foi assim que descobri que tenho talento e muito gosto por isso..."
    n "Aí, tipo, mesmo com poucos recursos, minha família conseguiu investir no meu sonho."
    n "Então, eu e Linne entramos na mesma escola de artes."
    n "Tudo parecia bem... até que ela começou a se afastar de mim."
    n "Eu não entendia o motivo, mas ela se recusava a falar sobre."
    n "Até que eu cansei dequela palhaçada, e decidi confrontar diretamente."
    n "Enfim... eu perdi a cabeça e nós brigamos..."
    n "Obviamente, a escola toda ficou sabendo. E, obviamente, eu sai como vilã..."
    n "Talvez por... eu ter explodido... fiquei com essa má fama."
    n "E pra piorar eles sempre me provocavam. E eu sempre reagia."
    n "Não foi uma boa época..."
    n "Minha família mal tinha dinheiro, a escola me odiava, as aulas estavam me matando e ainda tinha que trabalhar nas horas vagas."
    n "Era... o fundo do poço..."
    n "Eu só queria alguém pra conversar."
    n "Mas, quando recorri a Linne..."
    n "Contei toda a situação pra ela. E mesmo assim, fui menosprezada."
    m "Caramba..."
    n "Quando eu precisei de ajuda, ela não estava lá."
    n "Sei que não podemos nos prender ao passado."
    n "Só que isso... ainda não estou pronta pra perdoar."
    m "Meu Deus... n-não sei o que dizer..."
    n "Não precisa dizer nada..."
    n "Bom, deu o nosso tempo."
    n "Bora. Temos que voltar ao trabalho."

    "Durante o resto das atividades do dia, não conseguia para de pensar no que Nádia disse."
    "A Linne que conheço não faria algo daquele tipo..."
    "Então, por que ela o fez?"
    "..."
    "Vou descobrir o motivo."

label cap4_3:
    # mais tarde no dia
    "Finalmente, estou no meu quarto."
    "Posso ver as postagens sobre o programa, agora."
    "Hmm... onde foi que eu deixei o celular?"
    "Ouço batidas na porta."
    l "Moon, está aí?"
    m "AAAH!"
    "Linne abre a porta e entra no quarto."
    l "O que aconteceu? Porque se assustou assim?"
    m "Ah, n-não é nada..."
    l "Sei... eu só ia perguntar se você viu o meu secador."
    m "N-não vi, não."
    "Linne está mais calma. Acho que é uma boa "
    m "M-mas já que está aqui... Posso te perguntar uma coisa?"
    l "Claro. O que é?"
    m "Você e Nádia... eram amigas, certo?"
    l "S-sim."
    m "E porque vocês são tão distantes hoje?"
    l "Olha... e-eu não gosto muito de falar sobre..."
    l "Mas é que... na época eu notei que ela estava se tornando muito violenta..."
    m "Violenta? Tipo como?"
    l "Não sei explicar... Mas eu me senti muito intimidada."
    l "Por isso, eu me afastei dela."
    l "Parece que ela não aceitou isso muito bem... Então ela simplesmente ficou maluca!"
    l "Gritou comigo e me humilhou por motivos que eram válidos só pra ela!"
    l "Em nenhum momento pensou em me perguntar em como eu me sentia..."
    m "Sério?! Caramba, isso é pessímo..."
    l "Sim. Ela pensava apenas nela mesma."
    l "Então, me senti péssima por dias..."
    l "Por isso achei melhor acabar com nossa amizade."
    m "Entendo..."
    "Então, esse é o ponto de vista dela..."
    l "Você devia tomar cuidado com ela."
    l "Não quero que mais ninguém passe pelo que eu passei..."


    # dia seguinte, tarde antes apresentacao
    "Ok... falta pouco para a apresentação..."
    "Me sinto nervosa... apesar de tudo."
    "..."
    "Que tal eu... dar uma olhada nas discussões sobre o programa."
    "Quem sabe eu me sinto melhor..."
    "..."
    "Que estranho. Não tem ninguém falando sobre a próxima eliminação..."
    "Na verdade, as pessoas estão falando sobre um suposto caso de violência..."
    "Envolvendo Nádia e Linne."
    "Era o que eu estava discutindo com elas ontem!"
    "Hm. Como sempre, Nádia saiu completamente errada."

label cap4_4:

    # dia da apresentacao e eliminacao

    Sr "Muuuito boa noite a todos!"
    Sr "Eu sou o Sr.Star, este é o reality Star's Selection."
    Sr "E nesta noite, teremos uma grande performance..."
    Sr "Eeeee uma eliminaçãoooo!"
    Sr "Lembrando que teremos a performance final em apenas alguns dias."
    Sr "Então fiquem ligados!"
    "Alguns dias?! Nem acredito que já está acabando..."
    Sr "Dito isso, podemos iniciar as performances!"

    #Apos apresentacao, tem os resultados

    Sr "Muuuuito bem, hora dos resultados!"
    Sr "Estão animadas, queridas?"
    n "Anda logo! Tá demorando-"
    Sr "Calma, pavio curto."
    Sr "Em questão de segundos, vocês vera-"
    Sr "Oh! Esperem só um momento..."
    "Sr.Star conversa com a produção."
    Sr "..."
    Sr "Entendo. Obrigado pelo aviso."
    Sr "Infelizmente, meu público querido..."
    Sr "Tenho um anúncio urgente a fazer."
    Sr "Srta.Nádia está oficialmente desclassificada do programa."
    n "O-o que?"
    n "P-por que?"
    Sr "Não posso revelar o motivo neste momento, srta..."
    Sr "Porém, acredito que descobrirá em breve... hehee."
    n "Só pode ser brincadeira!"
    n "I-isso não é engraçado!"
    Sr "É isso, meninas vocês estão dispensadas!"
    Sr "O programa vai se encerrando por aqui-"
    n "Não! Exijo respostas!"
    #Sr "Err... srta. Qual a parte do 'estão dispensadas' você não entendeu?"
    Sr "Err... srta., nós ainda estamos ao vivo."
    n "Não interessa! Só saio daqui se me derem motivos!"
    Sr "Seguranças, acho que vamos ter que retirá-la à força."
    n "M-mas eu..."
    "Lágrimas preenchem seus olhos."
    n "*soluço* Quer saber? Que se foda!"
    n "E-eu *soluço* desisto dessa merda..."
    "Ela sai batendo os pés."
    m "E-espera!"
    "Linne está paralizada de choque."
    l "Ah..."
    m "Anda! temos que ajudar!"
    "Saimos do palco enquanto Sr.Star finaliza o programa."

    "Encontramos Nádia enxugando suas lágrimas um pouco a frente da entrada do palco."
    n "Me... me deixem em paz."
    m "E-eu sinto muito... mal posso imaginar o que é passar por isso."
    l "..."
    m "Ma-mas sei que você é forte p-"
    Sr "Ah, vocês estão aqui, meninas."
    Sr "Cara... Mais que show! Isso vai dar no que falar com certeza."
    Sr "Devo agradecer a srta.Pavio Curto por tudo."
    n "Seu-"
    Sr "Calma, não precisa ficar brava."
    Sr "Agora que estamos fora de cena... posso revelar o motivo de sua desclassificação."
    Sr "Surgiu um relato dentro do programa..."
    Sr "O qual apontava a srta. como uma agressora."
    n "Relato? Agressora?!"
    Sr "Exato! Nossa querida amiga Linne pode te explicar mais sobre o assunto."
    l "E-eu?!"
    "Linne?! Será que... O que ela me contou..."
    Sr "O ponto é: Não podemos manter uma agressora em nosso programa."
    Sr "Não tivemos escolha nesse caso."
    Sr "O que é uma pena... a srta. fez uma ótima pontuação e ia passar pra final..."
    "Linne parece desconfortável."
    Sr "Bem, era só isso mesmo que eu queria te dizer."
    Sr "Faça suas malas e boa sorte com o resto."
    Sr "Uma boa noite, estrelinhas."
    "Ele vai embora em mais nem menos."
    n "O que ele quis dizer com 'Linne pode te explicar mais sobre o assunto', hein?"
    l "Não sei... ele deve estar inventando coisas."
    "Então o relato delas foi ao ar..."
    #"E talvez... O que deu a entender foi que Linne saiu como vítima."
    "Por isso as pessoas só falavam disso na Internet."
    n "Escuta, eu... não tô brava."
    n "Só quero respostas."
    l "Eu juro que não sei de nada!"
    n "Não sabe, né...?"
    "Isso está tomando um péssimo rumo."
    "Elas não estão se entendendo. Talvez se eu tentar ajudar..."

label cap4_5:
    menu(nvl=True):
        "Intervir":
            "Elas não estão se entendendo. Talvez se eu tentar ajudar..."
            m "Olha, eu... Acho que vocês duas precisam conversar sobre o fim da amizade de vocês."
            l "C-como assim?"
            n "Mas o que isso tem a ver?"
            n "Eu odeio essa sua sindrome do protagonista!"
            n "Náo dá pra resolver tudo com o 'poder da amizade'!"
            m "N-não é isso que eu quero dizer!"
            n "Então o que é? Anda, desembuxa logo!"
            m "Err..."
            "Preciso dizer algo...."
            "Como eu posso colocar isso sem ofender ninguém?"
            "Por que isso tem que ser tão difícil?"
            l "Você nem mesmo sabe o que dizer."
            l "Pare de tentar se intromete-"
            n "Está tentando esconder algo, Linne? Deixe ela falar!"
            "OK... Tenho que dizer!"
            m "Vocês brigaram no passado..."
            m "Nádia falou que você, Linne, se afastou dela quando ela mais precisava."
            m "Mas Linne disse que se afastou por... Por medo do seu comportamento agressivo."
            n "O que... ?"
            m "E-e... Ela disse que se sentiu ameaçada..."
            n "Ameaçada?"
            l "I-isso é mentira! Eu nunca fiz isso!"
            n "Ah, agora eu entendo..."
            n "Cê deu um jeito de fazer parecer que EU sou um monstro..."
            l "Já falei, eu nã-"
            n "Quando na real, VOCÊ tava me USANDO só pra... Pra todos sentirem pena de você!"
            n "Se fez de coitada e me colocou como vilã só pra ganhar FAMA!"
            l "Não me fiz de coitada!"
            l "Se lembra da-das coisas horríveis que disse pra mim?!"
            l "Tem noção de como isso me impactou?"
            l "Lógico que não. Afinal, tudo o que importava era a sua opinião..."
            l "Te ajudei diversas vezes, Nádia. E nunca recebi um 'Obrigada'!"
            l "Além do mais, você jurava que era a ÚNICA que sofria."
            l "Quando eu tinha problemas, tudo o que você fazia era deixar as coisas piores!"
            n "Ah, qual foi? Toda vez eu te ajudava como podia!"
            l "Nunca! Você NUNCA me ajudou de verdade!"
            l "Toda v-vez que eu ia tentar desabafar com a minha melhor amiga..."
            l "Ao invés de ter empatia e-e pelo menos tentar me enteder..."
            l "Você me diminuia... E falava coisas do tipo:"
            l "'Ain, como cê é idiota... Não deveria deixar sua família mandar em você assim...'"
            l "'Se fosse eu no seu lugar, nem estaria tendo esse tipo de problema...'"
            n "Ah, ótimo! A SUA família te faz de fantoche e EU sou a culpada?"
            n "Eu só estava dizendo a verdade! Mas você aparentemente é muito fraca pra-"
            l "Viu? Você fez de novo!"
            l "Me diminuiu outra vez só por não pensar como você."
            n "..."
            l "..."
            "Que climão..."
            n "E... Isso serve como desculpa pra suas manipulações? Suas mentiras?"
            n "Ou talvez sirva como desculpa pra arruinar minha carreira?"
            l "..."
            l "Se não fosse por mim, você nem teria a oportunidade dessa carreira."
            l "Mas é orgulhosa demais pra reconhecer isso."
            n "Se não fosse por você... Eu não teria passado por tuda a dor que passei."
            n "Você não merece reconhecimento..."
            n "Ninguém que ofusca a luz dos outros pra poder brilhar mais merece reconhecimento."
            "Nádia vira as costas."
            n "Você merece todo meu desprezo, Linne."
            n "Isso é um adeus."
            l "Adeus, Nádia."
            "As duas saem caminhando em direções opostas."
        "Não intervir":
            m "..."
            l "Sinto muito, mas não tenho nada a dizer."
            n "É claro que não..."
        
    