label cap3_1:

    $ dia += 1
    $ periodo = "Manhã"
    $ atividade = "Antes do treino"
    
    "Enquanto me preparava para começar meu treinamento..."
    "Um funcionário do programa me informa que o Sr.Star quer que eu me apresente na área do palco o mais cedo possível."
    "{i}Me apresentar? Mas o evento será apenas á noite!{/i}"
    "{i}Sinto que há algo errado...{/i}"
    "Tento me manter calma enquanto caminho até o palco."
    "Chegando na área, vejo uma grande movimentação da equipe de produção para organizar o evento."

    Sr "Ah, Srta.Monnie, que bom que veio!"
    Sr "Temos muito o que discutir..."
    "{i}Oh, não! Será que fiz algo errado?{/i}"

    Sr "Mas não se preocupe, tentarei ser breve."
    Sr "Bom... Tenho observado que você 
    é, realmente, bem habilidosa."
    Sr "E seus feitos no programa chamaram a atenção do público..."
    Sr "Você, basicamente, viralizou nas redes sociais e conquistou uma comunidade de fãs!"
    Sr "Isso trouxe vários novos telespectadores e muuuito engajamento para o programa!"
    Sr "O fato é que o seu debut nessas condições é extremamente benéfico para a empresa."
    Sr "E é por isso que tenho uma oferta especial para você."
    m "C-como assim?"
    Sr "A senhorita tem a oportunidade de garantir a vitória no programa."
    Sr "E tudo o que precisa fazer é manter o hype até a apresentação final."
    Sr "Pode deixar que eu e a produção faremos nossa parte."
    "{i}Caramba! Tô recebendo a maior proposta da minha vida!{/i}"
    "{i}Mas... Ao mesmo tempo isso parece tão injusto com as meninas.{/i}"
    Sr "Então... O que acha?"
    Sr "Ah, você também pode receber dicas e spoilers sobre os eventos..."
    Sr "E talvez alguns outros benefícios..."
    Sr "É, definitivamente, uma oferta IRRECUSÁVEL, não é mesmo?"

    menu(nvl=True):
        "Não sei, não...":
            m "..."
            Sr "A senhorita parece canfusa..."
            m "N-não é nada disso!É que isso me parece meio..."
            m "Corrupto."
            Sr "Ora! Pensei que soubesse com o que estava se metendo quando decidiu se tornar treinee."
            Sr "Essa indústria esconde vários pobres, garota."
            Sr "Se você quiser ter sucesso, deve saber abraçar a ideia quando lhe é conveniente!"
            "{i}Acho que terei problemas com ele se eu recusar a oferta...{/i}"
            m "Tudo bem. Vou pensar sobre."
        "Eu aceito!":
            #m "Parece um bom negocio."
            m "Eu aceito a proposta."
            Sr "Sabia que aceitaria!"
            $ karma += 15
            $ aceitar = True

    m "Só que... O que exatamente significa 'manter o hype'?"
    Sr "O seu trabalho é descobrir isso."
    m "Oh..."
    Sr "Mas tenho algo que com certeza será útil..."
    Sr "Aqui! Leve isto."
    "Ele me entrega um celular comum."
    Sr "Ele tem acesso à Internet, então você pode saber o que as pessoas de fora estão achando."
    m "Mas celulares não são permitidos..."
    Sr "Ora, não se preocupe com isso!"
    Sr "Eu controlo tudo aqui dentro. Posso facilmente apagar qualquer evidência sobre isso."
    Sr "Ah! E é melhor manter isso longe das outras competidoras."
    Sr "Podemos ter problemas caso elas saibam..."
    m "S-sim."
    Sr "Minha nossa, acabei perdendo o horário!"
    Sr "Está dispensada, senhorita."
    Sr "E... Tome cuidado com esse celular, por favor."
    m "Serei o mais cuidadosa possível!"
    m "Agradeço pela oportunidade, Sr.Sta-"
    "Mal termino de falar e ele já me deu as costas."
    "{i}Er... Melhor eu voltar ao meu treinamento.{/i}"


label cap3_2:

    $ periodo = "Noite"
    $ atividade = "Evento ao vivo"

    Sr "Bem vindos, senhoras e senhores, à mais um evento ao vivo..."
    Sr "Do reality Stars Selection!"
    Sr "E hoje teremos... Algo mais tranquilo."
    Sr "Mas não menos impotante, obviamente!"
    # Apresentacao evento

    Sr "E nesta noite teremos um bate-papo com as estrelas aspirantes do reality."
    Sr "As perguntas pautados serão escolhidas por votação em tempo real pela nossa queridissima audiência!"

    Sr "Isso mesmo! Você aí que está nos assistindo pode votar pelo acesso ao nosso site ou QR code que está aparecendo na sua tela."
    Sr "Estão esperando o quê, meus queridos? Corram lá votar!"
    #Sr "Esse bate-papo foi organizado com o intuito de..."
    Sr "Começando, agora, pela primeira pergunta..."
    Sr "Uuuh, essa é uma clássica!"
    Sr "Preparadas?"
    l "Siiim!"
    Sr "Se você fosse um animal, qual você seria?"
    
    "Animal... ?"

    l "Haha, essa é fácil!"
    l "Acho que eu seria um coelinho."
    l "Eles são tão fofos e inocentes..."
    l "Nunca seriam capazes de ferir alguém."
    j "Aaaah! Meu Deus, eu adoro coelhos!"
    j "Você seria o mais fofo dos coelhos..."
    n "HÃ??"
    n "Garota, isso não faz o menor sentido!"
    l "Hm? Qual o problema?"
    l "Está dizendo que..."
    l "Que... eu não posso ser um coelhinho fofo?"
    l "*chorinho* Por que você é tão má?"
    Sr "Oh, não! Olha o que você fez Nádia!"
    Sr "Magoou a pooobre coitada..."
    n "*suspiro*"
    n "Tá, tá... Foi mal..."
    n "Satisfeita agora?"
    l "Você feriu meus sentimentos."
    l "Mas eu te perdoo."
    n "Hump!"
    Sr "Agora tõ curioso pra saber sobre a senhorita Nádia..."
    n "Eu? Err..."
    n "Não posso ser um... humano, não? Hehe..."
    Sr "Não, senhorita."
    Sr "Era pra senhorita ENTRAR na brincadeira, entende?"
    l "Ei, ei! já sei que animal você seria, Nádia!"
    n "Ah, é? E qual será?"
    l "Um gato!"
    n "Gatoh?"
    m "Woo! Faz sentido!"
    m "Acho que seria um gato..."

    menu(nvl=True):
        "Dos mais rabugentos.":
            m "Daqueles suuuper mal humorados e estressadinhos..."
            m "Que não deixam ninguém chegar perto, sabe?"
            m "Hihi, pra mim combina."
            n "Haha... muuuuuito engraçado, amigah."
            j "Aí... não sei..."
            j "Acho que eu... discordo um pouco."
            j "Ela não é tão..."
            j "Assim, ela pode ser um pouco arisca-"
            n_r "Ah, qual foi!"
            j "Calma, calma. Não terminei ainda!"
            j "Sabe, você é bem legal na maior parte do tempo."
            n "Finalmente! Alguém do meu lado."
            n "Você arrasa, Juni!"

        "Dos mais terriveis.":
            m "Daqueles bem... agitados..."
            m "Uh... Ah! Na vibe gato laranja!"
            m "Endendeu?"
            n_n "Sei."
            n "Hmmm, tipo..."
            n "Eu tinha um gatinho desse."
            n "Mas ele não era laranja."
            j "Jura? Aaaah, que graça!"
            j "Como ele era? Qual o nome?"
            j "Ele era gordinho? Acho muito fofo gatinhos bolota!"
            n "Err..."
            n "Tipo, ele se chamava Chuu."
            n "E o bicho simplesmente NÃO se sussegava!"
            n "Todo dia na mesma hora ele ligava o 440 e saia correndo pela casa."
            n "Aí ficava:"
            n "ZUUUUUMMMMM!"
            n "Aí ele parava."
            n "Olhava na minha cara..."
            n "E voltava a correr que nem louco."
            j "Hihihi, ele deve ser uma graça!"
            n "Éh... no caso o certo é 'devia'."
            n "Ele fugiu e nunca mais apareceu."
            m "Ah, caramba... eu sinto muito."
            Sr "Ei, meninas, nada de depressão por aqui!"

        "Dos mais tranquilinhos.":
            m "Sabe queles que são sossegados?"
            m "Que dormem o dia inteiro... Deixam a gente fazer carinho..."
            n "Moon, se você for mentir..."
            n "Mente direito, por favor!"
            m "A-ah? D-desculpa."

    Sr "Mudando de assunto..."
    Sr "Você concorda que seria um gato, srta.Nádia?"
    Sr "Até porque... não foi você quem escolheu."
    n "Hã? É, tanto faz."
    Sr "Ótimo, querida!"
    Sr "Vamos prooosseeeeguir!"
    "Uh, essa é a minha deixa."
    "Só que... o que eu digo?"
    "Meio que eu nunca tinha pensado sobre isso."
    M "Eu gostaria de ser..."

    menu(nvl=True):
        "Um cervo":
            m "Um lindo cervo!"
            j "U-um cervo? hmm..."
            m "Eles representam a gentileza e sensibilidad-"
            j "Não são aqueles animais gigantes e-e assustadores e... (o pior de tudo)"
            j "Chifrudos??"
            m "... o que quer dizer com isso?"
            n "IIIIH, ELA TÁ TIRANDO UMA COM A SUA CARA!"
            Sr "Eu não deixaaaava!"
            j "NÃ-NÃO! NÃO É ISSO!"
            J "DESCULPA! ME PERDOA, POR FAVOR?!"
            n "HAHAAHAAAH!"
            "O que é tão engraçado...?"
            "AH! AGORA EU ENTENDI!"
            n "AGORA EU TÔ ME DIVERTINFO!"
            # como o esperado ou com o esperado?
            "Oh, não... isso não saiu nada com o esperado."
            "Virei uma piada!"
            "Não quero nem ver o que a edição fará comigo..."
            j "M-me desculpa, mesmo..."

            menu(nvl=True):
                "Aceitar desculpas.":
                    m "Pode ficar tranquila."
                    m "Tá tudo bem... Acho."
                    j "E-eu en-entederia se-"
                    j "se você n-não aceitasse... s-sabe?"
                    m "Calma. Tá tudo bem."
                    j "Sério?"
                "Não aceitar":
                    m "Acho que... aceitar isso é demais..."
                    j "Hmm, e-eu entendo..."
                    n "Cara. Não pensei que cê fosse rancorosa assim."
                    $ karma += 5
            j "Juro que mão tocarei mais no assunto..."

        "Uma raposa":
            m "Uma rapozinha!"
            l "Como? Hahaha!"
            "Do que ela tá rindo?"
            l "Você sabe que elas representam astúcia e inteligência, não?"
            m "S-Sim... o que tem?"
            l "Nada, não..."
            l "Hihi!"
            l "Só não achei... muito coerente."
            l "Só isso."
            n "Nossaaa, e a sua resposta foi o que?"
            l "Silêncio! Sua cade-"

    Sr "Agora, só falta Juni!"
    Sr "O que a senhorita tem a dizer?"
    j "E-eu?"
    j "Hããã... eu gosto de doguinhos."
    j "Eles são fofos e... leais e..."
    j "B-bom, são divertidos."
    Sr "Divertidos, é? Heh."
    Sr "Coisa que está em falta na senhorita, não acha? Hahaha!"
    j "O-O que?!!"
    Sr "Sinto muitíssimo."
    Sr "Mas... a senhorita não apresenta nenhuma dessas características!"
    j "Ahhh..."
    Sr "Massss, não veja isso como um ataque, querida Juni!"
    Sr "Sabe? Você pode ser uma toupeira."
    Sr "Elas são esquisitas e muuuuuito feias..."
    Sr "Mas, pelo menos, elas basicamente vivem debaixo da terra!"
    Sr "Então, felizmente, ninguém nunca as vê!"
    l "Ha! Faz sentido!"
    # ela percebe que foi meio mal d+
    l "..."
    l "Elas também são muito habilidosas..."
    l "Em... Hãã... cavar buracos e... se esconder."
    l "Em algumas situações isso é bem admirável."
    n "EI! Isso tá longe de mais!"
    n "Reage, garota!"
    j "N-ão..."
    j "Na v-verdade, e-eles têm razão..."
    j "Eu concordo com eles."
    n "..."

    # continuacao das perguntas (a parte mais importante ja passou)

    Sr "Muito bem, isso é tuuuudo por hoje!"
    Sr "Agradeço pela participação do nosso público."
    Sr "Mas o queeee? Acabei de ficar sabendo que atingimos o pico de audiência!"
    Sr "E nosso site bateu o recorde de votos..."
    "Pico de audiência?? Recorde de votos??"
    "Caramba! Isso é muita gente!"
    "O que será que eles acharam de mim?"
    "Ai, não... será que eu falei demais?"
    "Ou falei pouco?"
    Sr "Nossas pequenas estrelas estão liberadas para descançar."
    Sr "Uma ótima... maravilhosa noite a todos!"

    "Voltamos para nosso dormitório."
    "Estava no corredor a caminho para meu quarto depois de ter usado o banheiro..."
    "Quando escuto vozes saindo da cozinha."
    n "Comendo outra vez, Jun?"
    n "Aquilo... te abalou muito?"
    j "N-não... eu to bem."
    n "Olha... na próxima vez..."
    n "Não deixa eles pisarem em você, tá?"
    n "Vamos dormir. Tá tarde..."

label cap3_3:
    "Ok... ok."
    "Estou no meu quarto... e isso significa que é hora de dormir."
    "Mas... mas..."
    "É tenta coisa pra pensar!"
    "Aconteceu tanta coisa... Nem me lembro do que fiz hoje..."
    "Ah, espera!"
    "O... o celular!"
    "Meu Deus, nem acredito que aceitei isso..."
    "Isso seria... corrupção? Ou algo do tipo?"
    #"Não sei."
    "Parando pra pensar... aposto que Nádia quebraria minha cara se soubesse."
    "Então, isso significa que isso É realmente errado!"
    "M-mas o que mais eu poderia fazer?"
    "Contrariar um dos homens mais poderosos da indústria?! Nem pensar!"
    # Ela aceita que foi corrompida (na visao dela)
    "..."
    "nem pensar."
    "Bom, já que estou com o dispositivo aqui..."
    "Uma olhadinha no que as pessoas estão falando não vai fazer diferença... né?"

    # leitura das noticias e coment[arios]
    "Encontrei uma discussão sobre o progrma na Internet!"
    #"'Em evento noturno, o reality STAR's SELECTION bate recordes de audi-'"
    #"Tá, tá. Disso eu já sei..."
    "O que os comentários dizem?"
    "'Bibi Pirigosa: mds vcd viram a cara da nádia flndo da dva line? parec q alguem tava mooreno de invejakkkkj'"
    "'C: tipo assim tinha 0 necessidade dela ser tao grossa o tempo td tlgd. pq ela n deixa a coitada ser o bixo que ela quer?'"
    "'Artur Morgana: credo quanto mimimikkkk. Nem a nadia ou a Juni tiveram o direito de escolher o animal delas.'"
    "Parando pra pensar... isso é verdade."
    "'Jet: defender Nádia = argumento anulado.'"
    "E essa seção continua nesse pique..."

    "Vou pra próxima."
    "'Kastanha: gnt so agr reparei q a Juni e uma toperakkkkkk as semelhancas sao mtas.'"
    "'C: nunca teria reparado nisso sozinho kkkkkk o sr.start eh um gênio.'"
    "AlienX: galera HELLO ela tava claramente desconfortável"
    "Bibi Pirigosa: logica q n véi vc n viu q ate ela concordo no finalzin?"
    
    "Próxima seção."

    #comentarios sobre ela msma

    "Esses comentários tão me deixando desconfortável..."
    "Melhor eu ir dormir."

label cap3_4:

    "Hoje temos o dia de folga."
    "Finalmente! Essa rotina ta acabando comigo"
    "Sinto meu corpo exausto..."
    "Mas... eu já dormi muito..."
    "Hmm... Já sei! Vou ver o que as outras estão fazendo."
    "Me dirijo a sala de STAR."
    "Observo diversos objetos e jogos de tabuleiro jogados no chão..."
    "E Nádia sentada sentada bem ao lado de um báu, procurando algo dentro dele."
    n "Bom dia, flor do dia!"
    n "Acordo agora, foi? Não te vi hoje."
    m "hãã... mais ou menos..."
    m "Ei, mas o que você tá fazendo?"
    m "Revirando o coitado do báu... ?"
    n "Ah, tipo..."
    n "Eu tava entediada, aí resolvi ver o que tinha de interessante aqui."
    n "Achei uns jogos bem legais. Pensei em chamar geral pra brincar."
    n "Bora participar?"
    "Nesse momento, Juni passa pela sala."
    n "Ei, Junão! Tá afim de um jogo de tabuleiro, hein, hein?"
    j "Desculpa... Eu já tenho planos..."
    j "Eu criei coragem e pedi pra produção a permissão para utilizar alguns materiais de arte."
    j "E eles autorirazam!"
    n "Jura?"
    j "Sim! E ainda tem mais!"
    j "Eles organizaram um espaço só para isso!"
    n "Ah, sei..."
    j "Eu tô tão feliz!"
    j "Já vou indo meninas!"
    j "Até mais tarde!"
    "Juni se vira e sai correndo."
    m "Divirta-se!"
    m "Porque ela sempre sai correndo?"
    n "Sei lá! Esse é o jeitinho dela..."
    n "Ha! já temos duas jogadoras. Falta só-"
    l "Olá, meninas!"
    n "*suspiro descontente* Ela."
    l "Hm? O que estâo fazendo sentadas no chão?"
    l "E que bagunça é essa?"
    n "Opa, hehe... Linnão..."
    n "Quer jogar um jogo de tabuleiro com a gente?"
    l "Jogo? Ah, não tenho tempo pra isso..."
    l "Eu vou treina-"
    n "Treinar?"
    n "Hoje é a nossa folga. Temos que aproveitar!"
    l "Sinto muito, meninas. Ma-"
    n "Ah, não... tudo bem."
    n "Nós já sabemos que você é completamente anti-diversão."
    l "O-O que?"
    l "Hmm... Eu vou participar."
    l "Só preciso passar no banheiro rápidinho."
    "Ela se dirige ao banheiro."
    n "Ei, Moon."
    n "Fica de olha nela."
    m "Hm? Por que?"
    n "Ela é a maior ratona... Não perde uma oportunidade de trapasear."
    m "Sério?"
    n "Sim, só que eu nunca consegui provar."
    "Fica complicado acreditar nela assim."
    n "Na verdade, to tentando pegar ela no flagra."
    n "Dessa vez ela não escapa."
    "Ela está determinada."
    l "Voltei, meninas. Podemos começar."
    l "O que vamos jogar?"
    n "Vamos jogar Influencer Life."
    m "Que jogo é esse? Nunca ouvi falar."
    n "Eu também não. Mas parece interessante."
    n "Ele é basicamente um jogo da vida, só de influencer."
    l "Muito original..."
    n "As regras são simples:"
    n "Cada jogador começa com o mesmo tanto de dinheiro e seguidores."
    n "E cada um pega uma carta de setor para trabalhar."
    n "Nessa carta vai estar o nosso contrato inicial e quanto nós recebemos."
    l "Já começamos contratadas? Que bom!"
    n "Bem, aí temos as cartas dos itens necessários para o nosso trabalho. Cada uma tem um preço."
    n "O jogador compra esses itens sempre que cair numa casa de compra."
    n "Tem também as fixas. Elas são indicam a quantidade de seguidores que temos. Cada uma vale mil seguidores."
    n "Quanhamos uma elas sempre que caimos em uma casa projeto bem sucedido."
    n "E perdemos uma a cada rodada em que estamos devendo dinheiro atrasado."
    n "Tirando isso... Temos as casas do tabuleiro. E você basicamente só tem que obedecer o que ela."
    l "E como faz pra ganhar?"
    n "Ganha quem chegar ao final com mais seguidores ou quem for o último jogador com seguidores."
    l "Tem mais alguma coisa que devemos saber?"
    n "Acho que não."
    l "Como assim 'acho que não'? Ora, não dá jogar sem as regras."
    n "A gente já sabe o principal..."
    n "Dá pra jogar, sim."
    "Como ela quer flagrar uma trapaça se ela nem sabe o que pode ou não ser uma?"


label cap3_5:
    $ dia += 1
    $ periodo = "???"
    $ atividade = "???"
    "..."
    "Escuto alguém chamar meu nome..."
    "Moon... ? Mooon..."
    l "Moonie!"
    m "AH!"
    l "Acorda! Você está atrasada!"
    m "... Atrasada... ?"
    l "Não está se sentindo bem?"
    m "Hããã... Que horas-"
    "Olho para meu despertador. Ele marca 10:30 da manhã."

    $ periodo = "Manhã"
    $ atividade = "Acordando"

    m "SÃO DEZ HORAS??!"
    m "Por que eu não acordei? O despertador não tocou?"
    l "Não sei... Eu não te vi por aí, então pensei que talvez houvesse algo errado."
    l "Melhor você levantar... Nossa presença foi solicitada no palco hoje à tarde."
    "Ah, ótimo... Como isso foi acontecer?"
    "Será essa coisa quebrou? Ou acabou as pilhas?"
    "Hmm... Não vejo problema no despertador."
    "Vou pedir pra alguém ver isso depois."

    $ periodo = "Tarde"
    $ atividade = "Reunião"

    Sr "Boa tarde, senhoritas!"
    Sr "Hoje estamos iniciando uma nova dinâmica."
    Sr "Vocês serão divididas em grupos de 2 participantes."
    n "Já fizemos isso uma vez..."
    Sr "Exato! Mas vocês performaram juntas?"
    n "Ah, não..."
    Sr "Pois bem, é isso o que vocês farão!"
    Sr "Vocês terão 7 dias para se preparar."
    Sr "As equipes serão livres para se organizarem da forma que preferirem durante esse período."
    Sr "Na data da performance, vocês serão avaliadas juntas..."
    Sr "E ao mesmo tempo, separadas!"
    Sr "Uma média será feita sobre a equipe."
    Sr "A equipe com maior média estará livre da eliminação."
    Sr "Quanto a outra, a participante com a menor nota será eliminada."
    Sr "Simples, não é?"
    Sr "Agora, é hora de definir as equipes!"
    "Nossos nomes aparecem no telão."
    Sr "A primeira equipe é formada por Linne e Nádia."
    Sr "E a segunda é formada por Juni e Moonie."
    Sr "Uhh, até rimou! Gostei!"
    "Tenho quase certeza de que ela já falou isso..."
    Sr "Sugiro que se organizem bem, queridas."
    Sr "Esse pode ser um desafio maior do que parece. He he he..."
    Sr "Bem, era o que eu tinha a dizer."
    Sr "Estão dispensadas!"

    $ periodo = "Tarde"
    $ atividade = "Organização"

    j "P-Parece que caimos na mesma equipe..."
    j "Bem... O que faremos?"
    m "Primeiro nós temos que nos organizar."
    m "Err... E precisamos de uma rotina."
    m "Tem alguma sugestão?"
    j "N-não. Podemos seguir a sua rotina."
    m "Certeza? As vezes você pode não acabar se adaptando..."
    j "Tenho certeza sim."
    m "Ok..."
    m "Precisamos pensar em uma performance que combine com a nossa dinâmica."
    j "A-Ah! Eu tenho uma ideia!"
    # juni faz uma boa sugestão

    m "Isso... Isso é ótimo!"
    m "Ótima ideia, Juni."
    j "O-Obrigada."
    m "Bom, podemos fazer o seguinte:"
    "Passamos o restante da tarde discutindo sobre a organização da performance."

    $ periodo = "Noite"
    $ atividade = "Jantar"

    j "Hmm... O que será que as outras duas estão fazendo?"
    m "Talvez elas ainda estão se organizando."
    j "Sei..."
    j "Coitadas... Deve estar sendo complicado pra elas."
    m "Hã? Por que?"
    j "Sabe, eu converso bastante com a Nádia."
    j "Ela me contou que ela e Linne eram amigas e tal..."
    j "Mas aí elas brigaram."
    m "Caramba..."
    m "Me lembro que Linne comentou que elas já se conheciam."
    j "É..."
    j "A propósito, o que acha da Linne?"

    menu(nvl=True):
        "Ela é legal.":
            m "Acho ela bem carismática."
            m "Além de ser muito boa em tudo..."
            m "Hoje de manhã o meu relógio não despertou."
            m "Aí ela veio me acordar pra reúnião."
            m "Se não fosse por ela, acho que estaria em apuros."
            j "Hmm. Entendo."
        "Não acho nada.":
            m "Não tenho nada a comentar sobre."
            "O que é mentira."
            m "Por que?"
            j "B-Bem..."
            j "Não sei o que achar dela..."
            if juni > 5:
                "Ela olha ao redor, como se procurasse por um fantásma."
                j "Esses dias eu fui pedir alguns dicas pra ela..."
                j "Sobre como ser mais confiante e tals."
                j "Ela respondeu que eu não devia me preocupar com isso."
                j "'O público adora Idols tímidos'... 'Coninue do jeito que está e vai dar tudo certo'."
                m "E qual o problema?"
                j "Meio que eu vivi minha vida inteira sendo assim... E isso não me trouxe nada de bom."
                j "O próprio sr.Star me falou que nínguem lembra de mim."
                "A cara dele dizer uma coisa dessas."
                # Juni tem um sexto sentido em relacao a linne
                j "Acredito que ela estava tentando ajudar, mas..."
    
    "Neste momento, Nádia entra no refeitório de cara fechada."
    j "Nádia! Como foi?"
    n "Ah, nem me pergunte."
    "Ela pega sua refeição e senta à mesa."
    n "Foi horrível!"
    n "Ela quer que tudo seja do jeito dela!"
    n "passamos a maior parte do tempo discutindo."
    j "Deve estar sendo difícil..."
    j "Mas, veja pelo lado bom: Vocês duas são muito talentosas."
    j "Vão se sair bem."
    n "Nossah, com certeza."
    "Ela fala isso em um tom irônico."
    n "O que resta é ter, tipo, muuuita paciência."
    j "Justo você que está em uma falta permanente de paciência..."
    n "Ah, cala a boca!"
    "Elas riem alto juntas."
    "Tô me sentindo meio solta nessa conversa aqui..."

    $ atividade = "Antes de dormir"
    "Até que tudo ocorreu bem hoje."
    "A juni é muito tranquila. Vai ser díficil entrar em conflito com ela."
    "Pensando bem... Ela até parou de gaguejar."
    "Será que se sente mais segura perto de mim agora?"
    
    # intensivo de dias de treino

    $ dia += 2
    $ periodo = "Tarde"
    $ atividade = "Treino de dança"

    