label cap5_1:
    "Dois dias se passaram desde a eliminação de Nádia."
    "Passei esses dias treinando e pensando sobre algumas coisas..."
    "Agora que somos só eu e Linne... O público também esta bem dividido."
    "Vejo muitas manchetes nas redes do tipo:"
    # add nomes COERENTES 
    "'STAR'S SELECTION: Participantes passam por problemas? Acompanhe a opinião de especialistas.'"
    "'STAR'S SELECTION: Perda de desempenho? Veja quais podem ser as causas e consequências.'"
    #"'O desempenho dela caiu bastante ultimamente.'"
    "Eles notaram que há algo errado, mesmo com as edições magicas do Sr.Star."
    "E relmente há algo errado!"
    "Nesses dois dias eu tentei conversar com Linne."
    "Mas nossas conversas não sairam do superficial..."
    "Isso me preocupa... Só que não sei o que fazer a respeito."
    "Passo a maior parte do dia sozinha agora, treinando..."
    "E fazendo... O possível pra não perder a cabeça."
    "A-Acho q estou pensando em muitas coisas, e ao mesmo tempo... Em nada."
    "Eu deveria estar feliz por ser uma das finalistas."
    "Acho que... Que talvez eu tenha me sentido muito confortável com meu trato de vencedora..."
    "Assisti sentada as garotas se esforçarem em vão em busca da vitória inacansável."
    "As vi tentar. E fracassar. E sofrer pelos seus erros."
    "Enquanto eu? Eu permaneci ilesa..."

    if(karma>30):
        "M-mas, não é como se fosse minha culpa."
        "Elas se arriscaram e entraram no programa por conta própria!"
        "Além do mais... Eu não teria chegado tão longe se não fosse pelo trato."
        "Esses idiotas não reconhecem meu esforço."
        "Treino pesado pra no fim... eles acharem que sou apenas 'só um rostinho bonito'."
        "Já chaga de se lamentar sobre o passado!"
        "Eu mereço vencer. Mais do que qualquer outra."
    else:
        "E, agora que estou tão perto do fim..."
        "..."
        "Me sinto péssima."
        "É como se eu tivesse as traído. Todas elas."
        "D-deve ter algo que possa fazer... Pra diminur a dor."