label cap4_1:

    $ dia += 1
    $ periodo = "Manhã"
    $ atividade = "Café da manhã"
    
    "Encontro Nádia na cozinha."
    nn "Finalmente acordou no horário, Moon?"
    m "*bocejo* Bom dia, pra você também..."
    nn "Garota... cê tá acabada, hein."
    m "Ah, isso é normal..."
    m "Queria ter a habilidade de acordar disposta todos os dias."
    m "Como a Linne... "
    m "Aliás, cadê ela?"
    nn "Uh, sei lá."
    nn "Talvez treinando?"
    m "M-mas já?"
    m "Ainda é muito cedo..."
    m "Você não acha isso preocupante?"
    nn "Um pouquinho... mas, tipo, eu vou fazer o quê?"
    nn "A doida não gosta que a gente questione ela."
    m "..."
    "Treinando? Mal amanheceu..."
    nn "Ahh, eu tô tããão feliz que abacou os treinos em duplas..."
    nn "Posso voltar a seguir minha rotina sem a interferencia de nenhuma chata."
    nn "Estava me sentindo presa, já!"
    m "É mesmo? Bom..."
    m "Eu vou sentir falta da Juni. Era... Bem interessante treinar com ela."
    nn "Cê tinha uma boa dupla. Quanto eu..."
    m "Você tá reclamando da sua dupla, mas ficaram em primeiro!"
    nn "Hã... Sim. Mas teve um custo."
    nn "No começo eu sentia vontadade de esganar aquela galinha!"
    nn "Mas depois, tipo, as coisas foram melhorando bastante."
    nn "Não foi tão ruim quanto achei que fosse ser."
    "Nádia mudou de ideia a respeito da Linne?"
    nn "Eu vou nessa, Moon."
    nn "Até mais tarde."
    m "A-Até."
    "Estranho... Pensei que elas tinham brigado feio..."
    "Tava todo mundo falando sobre da última vez que eu olhei o celular."
    "O que sará que eles descobriram? Eu não cheguei a ver..."
    "Naquele dia eu estava mais preocupada com a minha imagem do que qualquer outra coisa..."
    "Por causa do trato... Eu..."
    "Eu sinto que mudei..."

    if confianca_juni:
        "Poxa, Juni confia em mim!"
        "Imagine se ela descobrisse a verdade! Ela ficaria arrasada..."
        "Mas... Talves ela nunca descubra."
        "Longe dos olhos..."
    
    l "Moon?"
    m "Ah, bom dia, Linne."
    "Seu rosto está inchado e ela parece sonolenta."
    #"Será que... ela acordou agora? Isso é possível?"
    m "Acordou agora, Linne?"
    l "..."
    "Ela fica irritada pela pergunta."
    m "Oh, d-desculpa! Eu não queria..."
    m "S-sabe, é que isso não é tão comum."
    m "Acho que a gente trocou de lugar hoje. He he..."
    m "Já que você perdeu o horário..."
    l "..."
    m "..."
    l "Não estou com muita vontade de conversar hoje."
    "Ela simplesmente dá meia volta e sai."
    "Ok..."
    "Talvez eu converse com ela mais tarde."

    $ atividade = "Treinamento de canto"

    "Durante o treino de canto, minha voz chega a falhar algumas vezes."
    "O instrutor disse que não deve ser nada de mais..."
    "Mesmo assim ele me recomendou um tempo pra descançar a voz."
    "E ele chegou a comentar que Linne estava com o mesmo problema."
    "Deve ser uma boa oportunidade para falar com ela sobre."
    
    #$ periodo = "Tarde"
    $ atividade = "Descanso" 

    "Encontro Linne no studio de dança."
    m "Olá, Linne. Tem um minuto para conversar."
    l "O que foi?"
    m "Err..."
    "Ela continua irritada..."
    m "Bem, eu... Estou com um probleminha com minha voz..."
    m "Fiquei sabendo que você também está com isso-"
    l "Quem disse isso?"
    m "Hã? O instrutor disse..."
    m "Aí ele recomendou um descanso."
    l "Ah, isso é mentira."
    l "Eu não preciso de descanço nenhum."
    m "M-Mas..."
    l "Posso continuar meu treino em paz agora?"
    m "... Pode sim."

label cap4_2:

    $ periodo = "Tarde"
    $ ativdade = "Almoço"

    "Me encontrei com Nádia para almoçarmos."
    nn "Finalmente! Tô morta de fome."
    
    "Nos sentamos à mesa para comer."
    "Mas... Onde está Linne?"
    m "Hmm... Não cheguei a ver Linne depois do café... Você a viu?"
    nn "Ela deve estar treinando ou algo do tipo."
    nn "Por que?"
    m "É que... ela anda estranha."
    nn "Ah, deve ser o cansaço batendo na porta dela."
    nn "Depois de tanto treino pesado... Não dá pra esperar outra coisa."
    m "Isso é triste..."
    nn "Pois é... Mas é necessário. Pra debutar."
    nn "..."
    nn "Já pensou? O que será que vem após o debut?"
    m "O que quer dizer?"
    nn "Eu tava pensando sobre isso esses dias..."
    nn "Quem eu vou ter que me tornar depois do debut?"
    nn "O que eles farão comigo?"
    nn "A empresa vai criar uma nova identidade pra você... E tudo o que pode fazer é estar a altura das expectativas."
    nn "Não sobra muito tempo pra eu ser... Eu."
    nn "Me assusta um pouco a ideia de que, depois de tudo o que passei, eu acabe como apenas uma ferramenta."
    "Fe-ferramenta?"
    nn "Ah... Foi mal pelo desabafo. Eu só queria compartilhar com alguém."
    m "Não precisa se desculpar. E na verdade você tem um ótimo ponto."
    nn "É claro que eu tenho!"
    nn "Esse é o preço que temos que pagar pela fama..."
    nn "Meio difícil me acostumar com a ideia. Mas, tipo..."
    "Esse assunto está me chateando... Melhor eu mudar."
    m "E... Como se sente tão perto das finais?"
    m "Aliás, a próxima eliminação já é depois de amanhã."
    nn "Eu? Eu tô confiante!"
    m "Nossa... Você parece animada."
    nn "Saber que já tá chegando ao fim me anima."
    nn "Heh. Vocês duas que se cuidem, porque eu não vou pegar leve!"
    nn "Bem, eu já acabei minha refeição!"
    nn "Tô indo nessa, Moon."
    m "Tudo bem..."

    "Ferramenta... Ferramenta..."
    "Será que eu já me tornei... Uma ferramenta do sr.Star?"

label cap4_3:
    # mais tarde no dia
    $ periodo = "Noite"
    $ atividade = "Antes de dormir"

    "Após uma tarde de treinamento excessivos, finalmente estou no meu quarto."
    "Faz tempo que não olho as redes. É a minha oportunidade."
    "Hmm... onde foi que eu deixei o celular?"
    "Ouço batidas na porta."
    l "Moon, está aí?"
    m "AAAH!"
    "Linne abre a porta e entra no quarto."
    l "O que aconteceu? Porque se assustou assim?"
    m "Ah, n-não é nada..."
    l "Sei... eu só ia perguntar se você viu o meu secador."
    m "N-não vi, não..."
    l "Está escondendo algo, Moon?"
    m "Err... N-não."
    l "..."
    l "Então, boa noite."
    "Ela fecha a porta do quarto enquanto saia."
    "Caramba... Essa foi por pouco..."
    "Será que ela desconfia de algo?"
    "Vou dar só uma olhadinha rápida nas postagens... Vai que ela resolve voltar."
    "Vejo notícias e muitas pessoas discutindo sobre a suposta agressão cometida por Nádia..."
    "Deve ser o que Linne estava falando naquele dia. Será que ela foi agredida por Nádia mesmo?"
    "Parece que as pessoas realmente estão invertigando o caso."
    "Tem muitos comentários de hate direcionados a Nádia, mesmo não tendo nada confirmado."
    "Subiram até uma hashtag nas redes..."
    "Ela com certeza está em maus lençois."

    $ dia += 2
    $ periodo = "Manhã"
    $ atividade = "Acordando"

    "Acordo com Nádia gritando do corredor."
    nn "Vamo, gente! Bora acordar, já são nove e meia!"
    nn "E hoje tem apresentação, hein!"
    "9:30? Mas era pro meu despertador despertar as 7!"
    "Qual o problema dele?! Parece até que ele fica se desconfigurando sozinho!"
    "Saindo do quarto, percebo que Linne também está acordando agora."
    nn "Ué? Porque que ninguém ta acordando no horário?"
    m "O meu despertador tá com problema."
    nn "Sei... E você, Linne? Porque não acordou?"
    l "O que... ? Ah, o meu deve estar também..."
    nn "Sério? HA HA! Bem feito!"
    m "A gente deveria notificar o Sr.Star sobre-"
    l "N-Não! Não tem necessidade disso..."
    l "Anda. Temos que nos preparar."
    m "Hmm..."

    $ periodo = "Tarde"
    $ atividade = "Antes da apresentação"

    nn "Tá quase na hora..."
    m "Cadê a Linne? Ela não é de se atrasar..."
    nn "Ah, quem se importa? Uma hora ela aparece."
    nn "Vou arrasar nessa apresentação! Eu tô sentindo!"
    
    if nadia > 10:
        m "Você mudou bastante, Nádia."
        nn "Mudei?"
        m "Nem parece a mesma pessoa do início do programa."
        m "Sabe... Não perde a paciencia tão rápido..."
        m "Tá mais controlada..."
        m "Até sorri mais!"
        nn "Ah, é sobre isso."
        nn "Tipo, eu aprendi a ser mais tolerante com algumas coisas..."
        nn "Meio que o programa me forçou a isso, no final das contas."
        m "Entendo..."

        menu(nvl=True):
            "Essa é uma mudança bem-vinda":
                m "Eu gostei da mudança."
                nn "Hm? Tá querendo dizer o quê com isso, hein?!"
                m "N-Não me entenda mal!"
                m "É que... É bom ver você melhorando assim."
                nn "Ow. Que fofo!"
            "Como se sente com a mudança?":
                m "E o que está achando desse processo?"
                nn "Hã?"
                nn "Tipo..."
                nn "Eu não sei..."
                nn "Com a mudança, eu sinto que finalmente estou próxima dos meus objetivos..."
                nn "E ao mesmo tempo..."
                nn "Tipo, parece que tô distante... de mim mesma."
                nn "Mas, tipo... Isso é necessário até certo ponto..."
                nn "Já não sou bem vista por ser estrangeira!"
                nn "Só fica pior se eu for uma estrangeira barraqueira."
                # acho mt doido q nadia realmente mudou, pq a nadia do começo assumia q o problema sao as pessoas, n ela 
                # ela era revoltada com td e todos, agr ela so aceitou q pra subir na carreira, ela vai ter q agir da forma q tds esperam
                nn "Minha família já passou por xenofobia o suficiente por minha causa."
                nn "Nossos vizinhos sempre diziam:"
                nn "'Essa menina barulhenta é um terror! Se for pra causar essa bangunça, voltem logo pro seu país!'"
                nn "Agora, posso mudar as coisas."
                nn "Posso finalmete mudar a realidade lá em casa."
                nn "Pra mim, vale a pena mudar por uma causa."
        
    m "..."
    nn "..."
    nn "Posso te fazer uma pergunta, Moon?"
    m "P-Pode sim..."
    nn "Tipo, eu num quero ser chata..."
    nn "É que você parece sempre tão tranquila."
    nn "Assim... Você treina bastante e tem talento."
    nn "Mas nem parece que você tem ambições ou desejos próprios."
    nn "Dá a impressão de que a sua única preocupação é com as outras pessoas."
    nn "Isso não é cansativo?"
    m "..."
    
    l "Cheguei, meninas."
    l "Perdi muita coisa?"
    
    $ atividade = "Apresentação"

    Sr "Muito boa noite a toda nossa querida audiencia!"
    Sr "Eu sou o Sr.Star e você está assistindo o reality STAR'S SELECTION!"
    Sr "E essa noite, teremos mais uma eliminação!"
    Sr "Estamos cada vez mais próximos do gran finale!"
    Sr "Estão animados? Pois eu estou!"
    Sr "Agora, podemos dar início as apresentações."
    Sr "Srta. Moonie, pode subir ao palco!"

    "Realizamos as apresentações na sequência:"
    "Eu primeiro. Acredito que fui bem na medida do possível."
    "Linne foi em segundo. Pela primeira vez, eu a vejo cometendo pequenos erros na performance..."
    "Nádia em terceiro. Ela estava certa quando disse que ia arrasar."

    Sr "Essas foram as apresentações, senhoras e senhores!"
    Sr "Todas as participantes foram MA RA VI LHO SAS!"
    Sr "Infelizmente, uma de vocês será desclassificada..."
    Sr "Quem será a pobre eliminada? É o que vamos descobrir logo logo!"
    Sr "Fiquem ligados! Já já estaremos de volta!"

    $ periodo = "Noite"

    "Nádia está radiante."
    l "..."
    l "Então... Uma de nós vai ser eliminada..."
    l "Independente do resultado, quero que saibam que foram todas muito bem."
    nn "Pare de fingir que se importa, Linne. Isso tá ficando chato."
    l "Grr! Cale a boca! Eu só estou tentando ser legal."
    l "Diferente de você!"
    nn "Eu? Ah, nem vem!"
    m "Vocês duas brigam com bastante frequência..."
    nn "Não... Isso ficou no passado."
    "Passado?"
    m "Falando nisso... Vocês já brigaram feio?"
    m "Com agressões e-"
    nn "O que? Nunca!"
    m "Jura?"
    m "A Linne já contou que aconteceu uma vez..."
    l "HÃ?!"
    nn "Ela disse O QUE?"
    l "É-É mentira dela! Nunca falei nada do tipo!"
    m "Disse sim. Naquele dia quando estávamos almoçando... Cheguei a ficar preocupada-"
    l "N-Não acredite nela! Eu garanto que é tudo invenção!"
    nn "Invenção? Quem inventaria alguma coisa dessas além de você?!"
    l "Ela... Ela é uma mentirosa trapasseadora!"
    l "Não se lembra do que eu falei? Ela extrai o máximo possivel de todos pra ganhar vantagem!"
    l "Por isso ela se aproxima tanto das pessoas! Pra se aproveitar delas!"
    m "Ei! Eu nunca faria isso!"
    l "E-E eu te contei que ela tem um celular, sendo ele totalmente proíbido!"
    m "!"
    l "Eu te avisei e você não quis acreditar!"
    "ELA DESCOBRIU!"
    nn "Isso é verdade, Moonie?"
    m "Obvio que não! Não tem como eu ter uma coisa dessas..."
    l "Viu? Ela hesitou!"
    nn "..."
    nn "o que tá acontecendo aqui... ?"

    $ atividade = "Saída dos resultados"

    Sr "Estamos de volta ao programa!"
    Sr "Bem... Meninas, tenho más notícias..."
    Sr "Os resultados foram cancelados devido a um problema."
    Sr "Nádia está desclassificada devido ao rumor de agressão que ganhou força nas redes do programa."
    nn "C-COMO?"
    nn "ENTÃO ERA VERDADE!"
    Sr "Por favor, se acalme-"
    nn "INVENTOU UMA MENTIRA QUE ARRUINOU MINHA CARREIRA!"
    l "Eu não inventei nad-"
    "*PAFF*"
    "Nádia dá um tapão no rosto de Linne."
    nn "NÃO QUERO TE VER NUNCA MAIS!"
    nn "E VÃO SE FODER TODOS VOCÊS! ESTOU CANSADA DE TODAS ESSAS MENTIRAS!"
    "Ela sai batendo os pés e com lágrimas nos olhos."
    m "N-Nádia? Espera!"
    "Corro atrás dela."
    Sr "Err... Isso é tudo por hoje..."
    Sr "Corta a gravação."

    "Finalmente consigo alcança-la nos corredores para os palcos."
    nn "... O que foi, agora?!"
    m "Nádia eu..."
    nn "O que Linne disse sobre o celular... é verdade?"
    m "..."
    nn "Eu sabia... Então tudo aqui é falso!"
    m "Mas eu... Não tive escolha..."
    nn "Ah, é? Pois saiba que isso não te faz melhor do que ninguém... Muito pelo contrário!"
    m "Eu..."
    nn "Passou esse tempo todo enganando todas nós..."
    nn "Me responde... Você é um lixo humano como aquela cobra?"
    m "N-Não..."
    nn "Então prove! Ou nunca passará de um ser desprezível!"
    "Nádia vai em direção a saída sem dizer uma palavra."
    "Provar...?"

    jump cap5_1
    # no fim ela n mudou tanto assim

