label cap3_1:

    $ dia += 1
    $ periodo = "Manhã"
    $ atividade = "Antes do treino"
    
    "Enquanto me preparava para começar meu treinamento..."
    "Um funcionário do programa me informa que o Sr.Star quer que eu me apresente na área do palco o mais cedo possível."
    p "{i}Me apresentar? Mas o evento será apenas á noite!{/i}"
    p "{i}Sinto que há algo errado...{/i}"
    "Tento me manter calma enquanto caminho até o palco."
    "Chegando na área, vejo uma grande movimentação da equipe de produção para organizar o evento."

    Srn "Ah, Srta.Monnie, que bom que veio!"
    Srh "Temos muito o que discutir..."
    p "{i}Oh, não! Será que fiz algo errado?{/i}"

    Srn "Mas não se preocupe, tentarei ser breve."
    Srn "Bom... Tenho observado que você é, realmente, bem habilidosa."
    Srn "E seus feitos no programa chamaram a atenção do público..."
    Srh "Você, basicamente, viralizou nas redes sociais e conquistou uma comunidade de fãs!"
    Srh "Isso trouxe vários novos telespectadores e muuuito engajamento para o programa!"
    Srn "O fato é que o seu debut nessas condições é extremamente benéfico para a empresa."
    Srn "E é por isso que tenho uma oferta especial para você."
    m "C-como assim?"
    Srn "A senhorita tem a oportunidade de garantir a vitória no programa."
    Srn "E tudo o que precisa fazer é manter o hype até a apresentação final."
    Srh "Pode deixar que eu e a produção faremos nossa parte."
    p "{i}Caramba! Tô recebendo a maior proposta da minha vida!{/i}"
    p "{i}Mas... Ao mesmo tempo isso parece tão injusto com as meninas.{/i}"
    Srn "Então... O que acha?"
    Srn "Ah, você também pode receber dicas e spoilers sobre os eventos..."
    Srn "E talvez alguns outros benefícios..."
    Srh "É, definitivamente, uma oferta IRRECUSÁVEL, não é mesmo?"

    menu(nvl=True):
        "Não sei, não...":
            m "..."
            Srn "A senhorita parece confusa..."
            m "N-não é nada disso! É que isso me parece meio..."
            m "Corrupto."
            Sra "Ora! Pensei que soubesse com o que estava se metendo quando decidiu se tornar treinee."
            Sra "Essa indústria esconde vários pobres, garota."
            Srsc "Se você quiser ter sucesso, deve saber abraçar a ideia quando lhe é conveniente!"
            p "{i}Acho que terei problemas com ele se eu recusar a oferta...{/i}"
            m "Tudo bem. Vou pensar sobre."
        "Eu aceito!":
            #m "Parece um bom negocio."
            m "Eu aceito a proposta."
            Srh "Sabia que aceitaria!"
            $ karma += 15
            $ aceitar = True

    m "Só que... O que exatamente significa 'manter o hype'?"
    Srn "O seu trabalho é descobrir isso."
    m "Oh..."
    Srn "Mas tenho algo que com certeza será útil..."
    Srn "Aqui! Leve isto."
    "Ele me entrega um celular comum."
    Srn "Ele tem acesso à Internet, então você pode saber o que as pessoas de fora estão achando."
    m "Mas celulares não são permitidos..."
    Srh "Ora, não se preocupe com isso!"
    Srn "Eu controlo tudo aqui dentro. Posso facilmente apagar qualquer evidência sobre isso."
    Srh "Ah! E é melhor manter isso longe das outras competidoras."
    Srsc "Podemos ter problemas caso elas saibam..."
    m "S-sim."
    Srsu "Minha nossa, acabei perdendo o horário!"
    Srn "Está dispensada, senhorita."
    Srsc "E... Tome cuidado com esse celular, por favor."
    m "Serei o mais cuidadosa possível!"
    m "Agradeço pela oportunidade, Sr.Sta-"
    "Mal termino de falar e ele já me deu as costas."
    p "{i}Er... Melhor eu voltar ao meu treinamento.{/i}"


label cap3_2:

    $ periodo = "Noite"
    $ atividade = "Evento ao vivo"

    Srn "Bem-vindos, senhoras e senhores, à mais um evento ao vivo..."
    Srh "Do reality Stars Selection!"
    Srn "E hoje teremos... Algo mais tranquilo."
    Srh "Mas não menos impotante, obviamente!"
    # Apresentacao evento

    Srn "E nesta noite teremos um bate-papo com as estrelas aspirantes do reality."
    Srh "As perguntas pautadas serão escolhidas por votação em tempo real pela nossa queridissima audiência!"

    Srh "Isso mesmo! Você aí que está nos assistindo pode votar pelo acesso ao nosso site ou QR code que está aparecendo na sua tela."
    Srn "Estão esperando o quê, meus queridos? Corram lá votar!"
    #Srn "Esse bate-papo foi organizado com o intuito de..."
    Srn "Começando, agora, pela primeira pergunta..."
    Srh "Uuuh, essa é uma clássica!"
    Srn "Preparadas?"
    lh "Siiim!"
    Srn "Se você fosse um animal, qual você seria?"
    
    "Animal... ?"

    lh "Ha ha, essa é fácil!"
    ln "Acho que eu seria um coelinho."
    lh "Eles são tão fofos e inocentes..."
    lh "Nunca seriam capazes de ferir alguém."
    jh "Aaaah! Meu Deus, eu adoro coelhos!"
    jn "Você seria o mais fofo dos coelhos..."
    nsr "HÃ??"
    nsr "Garota, isso não faz o menor sentido!"
    ln "Hm? Qual o problema?"
    ln "Está dizendo que..."
    ln "Que... eu não posso ser um coelhinho fofo?"
    ln "*chorinho* Por que você é tão má?"
    Srn "Oh, não! Olha o que você fez, Nádia!"
    Srn "Magoou a pooobre coitada..."
    nn "*suspiro*"
    nn "Tá, tá... Foi mal..."
    nn "Satisfeita agora?"
    ln "Você feriu meus sentimentos."
    ln "Mas eu te perdoo."
    nn "Hump!"
    Srn "Agora estou curioso pra saber sobre a senhorita Nádia..."
    nn "Eu? Err..."
    nn "Não posso ser um... humano? Hehe..."
    Srn "Não, senhorita."
    Srn "Era pra senhorita ENTRAR na brincadeira, entende?"
    ln "Ei, ei! já sei que animal você seria, Nádia!"
    nn "Ah, é? E qual será?"
    ln "Um gato!"
    nn "Gato?"
    m "Ah, Faz sentido."
    m "Acho que seria um gato..."

    menu(nvl=True):
        "Dos mais rabugentos.":
            m "Daqueles suuuper mal humorados e estressadinhos..."
            m "Que não deixam ninguém chegar perto, sabe?"
            m "Hi hi, pra mim combina."
            nn "Ha ha... muuuuuito engraçado, viu."
            jn "Ai... não sei..."
            jn "Acho que eu... discordo um pouco."
            jn "Ela não é tão..."
            jn "Assim, ela pode ser um pouco arisca-"
            n_r "Ah, qual foi!"
            jn "Calma, calma. Não terminei ainda!"
            jn "Sabe, você é bem legal na maior parte do tempo."
            nn "Finalmente! Alguém do meu lado."
            nn "Você arrasa, Juni!"

        "Dos mais terriveis.":
            m "Daqueles bem... agitados..."
            m "Uh... Ah! Na vibe gato laranja!"
            m "Endendeu?"
            n_n "Sei."
            nn "Hmmm, tipo..."
            nn "Eu tinha um gatinho desse."
            nn "Mas ele não era laranja."
            jn "Jura? Aaaah, que graça!"
            jn "Como ele era? Qual o nome?"
            jn "Ele era gordinho? Acho muito fofo gatinhos bolota!"
            nn "Err..."
            nn "Tipo, ele se chamava Chuu."
            nn "E o bicho simplesmente NÃO se sussegava!"
            nn "Todo dia na mesma hora ele ligava o 440 e saia correndo pela casa."
            nn "Aí ficava:"
            nn "ZUUUUUMMMMM!"
            nn "Aí ele parava."
            nn "Olhava na minha cara..."
            nn "E voltava a correr que nem louco."
            jn "Hihihi, ele deve ser uma graça!"
            nn "Éh... no caso o certo é 'devia'."
            nn "Ele fugiu e nunca mais apareceu."
            m "Ah, caramba... eu sinto muito."
            $ nadia += 5
            Srn "Ei, meninas, nada de depressão por aqui!"

        "Dos mais tranquilinhos.":
            m "Sabe queles que são sossegados?"
            m "Que dormem o dia inteiro... Deixam a gente fazer carinho..."
            nn "Moon, se você for mentir..."
            nn "Mente direito, por favor!"
            m "A-ah? D-desculpa."
            "Hoje a Nádia não tá pra brincadeira."

    Srn "Mudando de assunto..."
    Srn "Você concorda que seria um gato, srta.Nádia?"
    Srn "Até porque... não foi você quem escolheu."
    nn "Hã? É, tanto faz."
    Srn "Ótimo, querida!"
    Srn "Vamos prooosseeeeguir!"
    "Uh, essa é a minha deixa."
    "Só que... o que eu digo?"
    "Meio que eu nunca tinha pensado sobre isso."
    M "Eu gostaria de ser..."

    menu(nvl=True):
        "Um cervo":
            m "Um lindo cervo!"
            jn "U-um cervo? hmm..."
            m "Eles representam a gentileza e sensibilidad-"
            jn "Não são aqueles animais gigantes e-e assustadores e... (o pior de tudo)"
            jn "Chifrudos??"
            m "... o que quer dizer com isso?"
            nn "IIIIH, ELA TÁ TIRANDO UMA COM A SUA CARA!"
            Srn "Eu não deixaaaava!"
            jn "NÃ-NÃO! NÃO É ISSO!"
            Jn "DESCULPA! ME PERDOA, POR FAVOR?!"
            nn "HAHAAHAAAH!"
            "O que é tão engraçado...?"
            "AH! AGORA EU ENTENDI!"
            nn "AGORA EU TÔ ME DIVERTINFO!"
            # como o esperado ou com o esperado?
            "Oh, não... isso não saiu nada com o esperado."
            "Virei uma piada!"
            "Não quero nem ver o que a edição fará comigo..."
            jn "M-me desculpa, mesmo..."

            menu(nvl=True):
                "Aceitar desculpas.":
                    m "Pode ficar tranquila."
                    m "Tá tudo bem... Acho."
                    jn "E-eu en-entederia se-"
                    jn "se você n-não aceitasse... s-sabe?"
                    m "Calma. Tá tudo bem."
                    jn "Sério?"
                "Não aceitar":
                    m "Acho que... aceitar isso é demais..."
                    jn "Hmm, e-eu entendo..."
                    nn "Cara. Não pensei que cê fosse rancorosa assim."
                    $ karma += 5
            jn "Juro que mão tocarei mais no assunto..."

        "Uma raposa":
            m "Uma rapozinha!"
            ln "Como? Hahaha!"
            "Do que ela tá rindo?"
            ln "Você sabe que elas representam astúcia e inteligência, não?"
            m "S-Sim... o que tem?"
            ln "Nada, não..."
            ln "Hihi!"
            ln "Só não achei... muito coerente."
            ln "Só isso."
            nn "Nossaaa, e a sua resposta foi o que?"
            ln "Silêncio! Sua-"

    Srn "Agora, só falta Juni!"
    Srn "O que a senhorita tem a dizer?"
    jn "E-eu?"
    jn "Hããã... eu gosto de doguinhos."
    jn "Eles são fofos e... Engrassados e..."
    jn "B-bom, são divertidos."
    Srn "Divertidos, é? Heh."
    Srn "Coisa que está em falta na senhorita, não acha? Hahaha!"
    jn "O-O que?!!"
    Srn "Sinto muitíssimo."
    Srn "Mas... a senhorita não apresenta nenhuma dessas características!"
    jn "Ahhh..."
    Srn "Massss, não veja isso como um ataque, querida Juni!"
    Srn "Sabe? Você pode ser uma toupeira."
    Srn "Elas são esquisitas e muuuuuito feias..."
    Srn "Mas, pelo menos, elas basicamente vivem debaixo da terra!"
    Srn "Então, felizmente, ninguém nunca as vê!"
    ln "Ha! Faz sentido!"
    # ela percebe que foi meio mal d+
    ln "..."
    ln "Elas também são muito habilidosas..."
    ln "Em... Hãã... cavar buracos e... se esconder."
    ln "Em algumas situações isso é bem admirável."
    nn "EI! Isso tá longe de mais!"
    nn "Reage, garota!"
    jn "N-ão..."
    jn "Na v-verdade, e-eles têm razão..."
    jn "Eu concordo com eles."
    nn "..."

    # continuacao das perguntas (a parte mais importante ja passou)

    Srn "Próxima perrrgunta!"
    Srn "Lembrando que a pergunta mais votada será escolhida para o evento."
    Srn "'Qual é o seu hobby favorito?'"
    jn "!"
    "Juni parece animada."
    ln "Hobby... ?"
    Srn "Isso mesmo. Aposto que alguém tão talentosa e inteligente como a senhorita deve ter vários hobbys!"
    # linne n tem hobbys, por isso fica nervosa com a pergunta
    ln "Claro, claro... heh..."
    ln "Eu... Gosto muito de... "
    ln "Hãã..."
    #"Nunca vi Linne tão sem jeito. O que deu nela?"
    ln "Dançar! Eu ADORO dançar!"
    ln "Esse é o meu hobby favorito."

    menu(nvl=True):
        "É um ótimo hobby!":
            m "Que legal, Linne."
            m "Eu sabia que você é muito boa na dança, mas não sabia que era algo tão natural seu."
            ln "Pois é. Eu nasci para ser uma dançarina."
            jn "Queria ter essa dedicação..."
            $ linne += 5
        "Só isso?":
            m "Err... Mas dançar já é faz parte do nosso trabalho."
            m "Não teria alguma outra coisa que não esteja relacionada a isso?"
            ln "N-Não. Nada me vem à cabeça..."

    nn "É... Dançar é bem legal e tal."
    nn "Só que chega uma hora que cansa, né?"
    nn "..."
    nn "Não tive muito tempo pra hobbys depois que comecei como trainee."

    nn "Mas eu me lembro que gostava bastante de jogar jogos fps com alguns amigos." # ela é energetica e explosiva, ent achei que combinasse com ela
    # o 
    nn "E ensinava meus irmãos a jogar quando eles pediam."
    nn "Era muito bom pra desestressar."
    nn "E também pra passar ainda mais raiva."
    Srn "Se me permite o comentário..."
    Srn "A senhorita tem cara de quem xingava a equipe no chat."
    nn "O-O que?! N-Nada a ver..."
    Srn "Sei..."

    jn "..."
    Srn "Gostaria de dizer algo, srta.Juni?"
    # juni esta com vergonha de falar dps do que aconteceu na ultima pergunta
    jn "Hmm... Eu..."
    #jn "Eu t-tenho vários hobbys."
    jn "A-Adoro moda."
    jn "Passo muito tempo pesquisando e-e criando novos looks."
    jn "Sempre que posso, eu-"
    # ele n esta interessado nela
    Srn "Isso é realmente muuuuito interessante, querida."
    Srn "Mas..."
    "Juni se entristece com a interrupção."

    Srn "Ah, srta.Moonie!"
    Srn "Não quer dizer algo sobre o seu hobby?" 
    m "Eu? Bom..."

   

    Srn "Muito bem, isso é tuuuudo por hoje!"
    Srn "Agradeço pela participação do nosso público."
    Srn "Mas o queeee? Acabei de ficar sabendo que atingimos o pico de audiência!"
    Srn "E nosso site bateu o recorde de votos..."
    "Pico de audiência?? Recorde de votos??"
    "Caramba! Isso é muita gente!"
    "O que será que eles acharam de mim?"
    "Ai, não... será que eu falei demais?"
    "Ou falei pouco?"
    Srn "Nossas pequenas estrelas estão liberadas para descançar."
    Srn "Uma ótima... maravilhosa noite a todos!"

    "Voltamos para nosso dormitório."
    "Estava no corredor a caminho para meu quarto depois de ter usado o banheiro..."
    "Quando escuto vozes saindo da cozinha."
    nn "Comendo outra vez, Jun?"
    nn "Aquilo... te abalou muito?"
    jn "N-não... eu estou bem."
    nn "Olha... na próxima vez..."
    nn "Não deixa eles pisarem em você, tá?"
    nn "Vamos dormir. Tá tarde..."

label cap3_3:
    "Ok... ok."
    "Estou no meu quarto... e isso significa que é hora de dormir."
    "Mas... mas..."
    "É tenta coisa pra pensar!"
    "Aconteceu tanta coisa... Nem me lembro do que fiz hoje..."
    "Ah, espera!"
    "O... o celular!"
    "Meu Deus, nem acredito que aceitei isso..."
    "Isso seria... corrupção? Ou algo do tipo?"
    #"Não sei."
    "Parando pra pensar... aposto que Nádia quebraria minha cara se soubesse."
    "Então, isso significa que isso É realmente errado!"
    "M-mas o que mais eu poderia fazer?"
    "Contrariar um dos homens mais poderosos da indústria?! Nem pensar!"
    # Ela aceita que foi corrompida (na visao dela)
    "..."
    "nem pensar."
    "Bom, já que estou com o dispositivo aqui..."
    "Uma olhadinha no que as pessoas estão falando não vai fazer diferença... né?"

    # leitura das noticias e coment[arios]
    "Encontrei uma discussão sobre o progrma na Internet!"
    #"'Em evento noturno, o reality STAR's SELECTION bate recordes de audi-'"
    #"Tá, tá. Disso eu já sei..."
    "O que os comentários dizem?"
    "'Bibi Pirigosa: mds vcd viram a cara da nádia flndo da dva line? parec q alguem tava mooreno de invejakkkkj'"
    "'C: tipo assim tinha 0 necessidade dela ser tao grossa o tempo td tlgd. pq ela n deixa a coitada ser o bixo que ela quer?'"
    "'Artur Morgana: credo quanto mimimikkkk. Nem a nadia ou a Juni tiveram o direito de escolher o animal delas.'"
    "Parando pra pensar... isso é verdade."
    "'Jet: defender Nádia = argumento anulado.'"
    "E essa seção continua nesse pique..."

    "Vou pra próxima."
    "'Kastanha: gnt so agr reparei q a Juni e uma toperakkkkkk as semelhancas sao mtas.'"
    "'C: nunca teria reparado nisso sozinho kkkkkk o sr.start eh um gênio.'"
    "AlienX: galera HELLO ela tava claramente desconfortável"
    "Bibi Pirigosa: logica q n véi vc n viu q ate ela concordo no finalzin?"
    
    "Próxima seção."

    #comentarios sobre ela msma

    "Esses comentários tão me deixando desconfortável..."
    "Melhor eu ir dormir."

label cap3_5:
    $ dia += 1
    $ periodo = "???"
    $ atividade = "???"
    "..."
    "Escuto alguém chamar meu nome..."
    "Moon... ? Mooon..."
    ln "Moonie!"
    m "AH!"
    ln "Acorda! Você está atrasada!"
    m "... Atrasada?"
    ln "Não está se sentindo bem?"
    m "Hããã... Que horas-"
    "Olho para meu despertador. Ele marca 10:30 da manhã."

    $ periodo = "Manhã"
    $ atividade = "Acordando"

    m "SÃO DEZ HORAS??!"
    m "Por que eu não acordei? O despertador não tocou?"
    ln "Não sei... Eu não te vi por aí, então pensei que talvez houvesse algo errado."
    ln "Melhor você levantar... Nossa presença foi solicitada no palco hoje à tarde."
    "Ah, ótimo... Como isso foi acontecer?"
    "Será essa coisa quebrou? Ou acabou as pilhas?"
    "Hmm... Não vejo problema no despertador."
    "Vou pedir pra alguém ver isso depois."

    $ periodo = "Tarde"
    $ atividade = "Reunião"

    Srn "Boa tarde, senhoritas!"
    Srn "Hoje estamos iniciando uma nova dinâmica."
    Srn "Vocês serão divididas em grupos de 2 participantes."
    nn "Já fizemos isso uma vez."
    Srn "Exato! Mas vocês performaram juntas?"
    nn "Ah, não..."
    Srn "Pois bem, é isso o que vocês farão!"
    Srn "Vocês terão 7 dias para se preparar."
    Srn "As equipes serão livres para se organizarem da forma que preferirem durante esse período."
    Srn "Na data da performance, vocês serão avaliadas juntas..."
    Srn "E ao mesmo tempo, separadas!"
    Srn "Uma média será feita sobre a equipe."
    Srn "A equipe com maior média estará livre da eliminação."
    Srn "Quanto a outra, a participante com a menor nota será eliminada."
    Srn "Simples, não é?"
    Srn "Agora, é hora de definir as equipes!"
    "Nossos nomes aparecem no telão."
    Srn "A primeira equipe é formada por Linne e Nádia."
    Srn "E a segunda é formada por Juni e Moonie."
    Srn "Uhh, até rimou! Gostei!"
    "Tenho quase certeza de que ela já falou isso..."
    Srn "Sugiro que se organizem bem, queridas."
    Srn "Esse pode ser um desafio maior do que parece. He he he..."
    Srn "Bem, era o que eu tinha a dizer."
    Srn "Estão dispensadas!"

    $ periodo = "Tarde"
    $ atividade = "Organização"

    jn "P-Parece que caimos na mesma equipe..."
    jn "Bem... O que faremos?"
    m "Primeiro nós temos que nos organizar."
    m "Err... E precisamos de uma rotina."
    m "Tem alguma sugestão?"
    jn "N-não. Podemos seguir a sua rotina."
    m "Certeza? As vezes você pode não acabar se adaptando..."
    jn "Tenho certeza sim."
    m "Ok..."
    m "Precisamos pensar em uma performance que combine com a nossa dinâmica."
    jn "A-Ah! Eu tenho uma ideia!"
    # juni faz uma boa sugestão

    m "Isso... Isso é ótimo!"
    m "Ótima ideia, Juni."
    jn "O-Obrigada."
    m "Bom, podemos fazer o seguinte..."
    "Passamos o restante da tarde discutindo sobre a organização da performance."
    # detalhes da performance

    $ periodo = "Noite"
    $ atividade = "Descanso"

    # na sala de star (adoro esse trocadilho)
    m "Ufa! Finalmete podemos descansar."
    jn "Estou cansada também..."
    jn "Hmm... O que será que as outras duas estão fazendo?"
    m "Talvez elas ainda estão se organizando."
    jn "Sei..."
    jn "Coitadas... Deve estar sendo complicado pra elas."
    m "Hã? Por que?"
    jn "Sabe, eu converso bastante com a Nádia."
    jn "Ela me contou que ela e Linne eram amigas..."
    jn "Mas aí elas brigaram. Elas devem ter personalidades muito conflitantes."
    m "Caramba..."
    m "Me lembro que Linne comentou que elas já se conheciam."
    jn "É..."
    jn "A propósito, o que acha da Linne?"

    menu(nvl=True):
        "Ela é legal.":
            m "Acho ela bem carismática."
            m "Além de ser muito boa em tudo..."
            m "Hoje de manhã o meu relógio não despertou."
            m "Aí ela veio me acordar pra reúnião."
            m "Se não fosse por ela, acho que estaria em apuros."
            jn "Hmm. Entendo."
        "Pra mim, tanto faz.":
            m "Não tenho nada a comentar sobre."
            "O que é mentira."
            m "Por que?"
            jn "B-Bem..."
            jn "Não sei o que achar dela..."
            if juni > 5:
                "Ela olha ao redor, se sertificando que não tem ninguém por perto."
                jn "Esses dias eu fui pedir alguns dicas pra ela..."
                jn "Sobre como ser mais confiante, sabe?"
                jn "Ela respondeu que eu não devia me preocupar com isso."
                jn "'O público adora os tímidos'... 'Coninue do jeito que está e vai dar tudo certo'."
                m "E qual o problema?"
                jn "Meio que eu vivi minha vida inteira sendo assim... E isso não me trouxe nada de bom."
                jn "As pessoas constantemente me ignoram e me humilham, porque sabem que eu não faço nada a respeito..."
                jn "O próprio sr.Star me trata como um ninguém!"
                jn "E-Eu quero mudar isso."
                # Juni tem um sexto sentido em relacao a linne
                jn "Acredito que Linne estava tentando ajudar, mas..."
    
    "Neste momento, Nádia entra na sala de cara fechada."
    jn "Nádia, como foi?"
    nn "Ah, nem me pergunte."
    "Ela se joga no sofá, ocupando a maior parte dele."
    nn "Foi horrível!"
    nn "Ela quer que tudo seja do jeito dela!"
    nn "passamos a maior parte do tempo discutindo."
    jn "Ah..."
    jn "Mas, veja pelo lado bom: vocês duas são muito talentosas."
    jn "Vão se sair bem."
    nn "Nossa, com toda certeza."
    "Ela fala isso em um tom irônico."
    nn "O que resta é ter, tipo, muuuita paciência."

    menu(nvl=True):
        "Está exagerando.":
            m "Pare com isso... Nem deve ser tão difícil assim."
            nn "Ah, não? Quer trocar de lugar comigo?"
            nn "Hmp! Você nunca entenderia."
        "Que situação difícil.":
            m "Caramba... Deve estar sendo complicado..."
            # ela fala brincando
            m "Justo você que está em uma falta permanente de paciência..."
            nn "E-Ei!"
            jn "Hi hi! Ela tem razão."
            nh "Ah, calem a boca!"   
    
    nn "Aff... Não queria ter que trabalhar junto com ela."
    m "Hm? Por que?"
    nn "Não lembro se eu já te contei mas... A gente era amiga."
    nn "Sabe, minha família é estrangeira e tivemos dificuldades de nos estabelecer aqui."
    nn "A família dela se se dispôs a nos ajudar no início. E foi assim que a gente se conheceu."
    nn "Aí ela me ajudou com adaptação e tal... Até que viramos amigas."
    nn "Ela até me levava pra fazer as aulas de dança e canto com ela."
    jn "Foi aí que você descobriu seus telentos, não é Nádia?"
    nn "Foi sim... Os professores me elogiavam bastante."
    nn "Eu até ganhei um desconto pra estudar lá junto com ela."
    m "Caramba, que legal! Mas e aí?"
    nn "Aí... Tipo, ela começou a agir de um jeito estranho."
    nn "Ela ficava, tipo, muito irritada quando alguém me elogiava."
    nn "E eu tinha a impressão de que ela tava  falando de mim pelas costas..."
    nn "Hoje em dia, eu acabaria com ela se eu desconfiasse de uma atitude dessa."
    nn "Só que na época, a nossa amizade significava algo pra mim.... Por isso eu relevei."
    nn "Até que eu comecei a me sentir excluída por ela."
    nn "E foi bem numa época que eu estudava e trabalhava pra pagar as contas de casa..."
    nn "Era tudo muito estressante..."
    nn "E ela como amiga deveria estar me ajudando, e não o contrário!."
    jn "Isso mesmo!"
    nn "Fui falar com ela sobre e ela... Tentou desconversar..."
    nn "Aí eu perdi minha cabeça e nós brigamos bem feio."
    m "Nossa... Isso é horrível!"
    jn "E olha que o pior ainda não chegou!"
    jn "Sabe o que ela fez depois, Moon?"
    m "Não..."
    jn "Ela falou que a Nádia é pessima e que ELA estragou a amizade!"
    "Juni está muito brava."
    nn "Calma, garota. Também não precisa gritar."
    jn "Oh... D-Desculpa. É que eu fico muito... Irritada com isso."
    jn "Tenho certeza de que ela fez isso por inveja!"
    nn "Ineveja? Há! Dúvido muito."
    nn "Ela vem de uma família artistica muito bem sucedida."
    nn "Tipo, eles tem dinheiro; e ela todas as oportunidades do mundo."
    nn "Enquanto eu tinha que estudar e ralar muuuito para conquistar qualquer coisa."
    nn "Tinha que me matar de trabalhar e ainda tinha que ir treinar!"
    jn "Foram tempos difíceis, não?"
    nn "Foram mesmo! Sorte que eu tinha minha família pra me acalmar."
    nn "Se não, alguém taria sem cabeça agora. Ha ha!"    
    "Que medo..."
    nn "*bosejo* Estou muito cansada..."
    nn "Já vou dormir, gente."
    m "Ah, eu também já vou."
    m "Boa noite, meninas."

    $ atividade = "Antes de dormir"
    "Até que tudo ocorreu bem hoje."
    "A juni é muito tranquila. Vai ser díficil entrar em conflito com ela."
    "Pensando bem... Ela até parou de gaguejar."
    "Será que ela se sente mais segura perto de mim agora?"
    "..."
    "E se... Eu olhasse o que as pessoas dizem nas redes?"
    "Ligo o celular e começo a fazer buscas."
    "Encontrei uma manchete:"
    "'STAR'S SELECTION: Nova dinâmica do programa desperta o interesse do público'"
    "Alguns trechos da notícia:"
    "'A dupla formada por Moonie e Juni demonstra fortes traços de cooperação e entendimento mutuo.'"
    "'Em contrapartida, a dupla Linne e Nádia passou por diversas turbulencias em um pequeno espaço de tempo...'"
    "'As participantes da dupla afirmaram que já se conheciam antes do programa...'"
    "'Ambas relataram, em conversas dentro do reality, que seu laço de amizade foi cortado após uma discussão.'"
    "'Os motivos da discussão ainda não foram revelados...'"
    "Agora, os comentários:"
    "'???: O primeiro dia de dinâmica já nos rendeu muito conteúdo! Mal posso esperar pelas atualizações!'"
    "'???: A melhor prt é q as duplas são exatamente o oposto uma da outra.'"
    "'???: O que será que levou as duas discutirem? Eu preciso saber!'"
    "Essa é uma boa pergunta..."
    "Não custa nada perguntar alguma hora."
    "Isso deve ajudar a gerar engajamento, também."
    "Oh, olha a hora! Preciso dormir logo."
    "Preciso cuidar para evitar olheiras..."
    
    # intensivo de dias de treino

    $ dia += 2
    $ periodo = "Tarde"
    $ atividade = "Treino de dança"
    
    jn "Ai, d-desculpa... Estou fora de posição de novo..."
    "Ontem começamos nosso treinamento em dupla."
    "Sinto que, durante o treinamento..."
    "Seja ele qual for..."
    "Ela fica sempre muito nervosa, e acaba cometendo erros que não cometeria se estivesse só."
    jn "Ju-juro que não vou errar na próxima."
    "Estamos treinando a horas e ela já disse isso umas 500 vezes."
    m "Tá tudo bem... Quer dar uma pausa? Talvez seja melhor."
    jn "Sim, sim..."
    jn "E-Eu preciso ir ao banheiro. Já volto, ok?"
    "Ela sai apressada do studio de dança."
    "Aff... Isso vai ser mais complicado do que eu imaginei."
    "A insegurança dela está se tornando um problema cada vez maior."
    "E querendo ou não, acaba me atrapalhando. Pois sinto que não posso confiar nela..."
    "Ahh... Tudo é tão cansativo!"
    "Mesmo que eu já tenha meu trato com o Sr.Star, isso ainda pode ser um problema."
    "E parando pra pensar..."
    "Se minha dupla minha dupla for muito mal, a minha reputação será afetada."
    "E-E se o pior acontecer... Pode ser que o Sr.Star quebre o trato!"
    "Ai, não... Preciso fazer alguma coisa."
    jn "Voltei."
    jn "Desculpa pela demora..."
    "Tô começando a me incomodar com a quantidade de 'desculpas' dela."
    jn "P-Podemos voltar a treinar... Temos muito o que melhorar ainda."
    # eu acredito que formar uma conexão profunda ajuda mais do q forçar a barra aq
    menu(nvl=True):
        "Voltar ao treino":
            m "Claro. Não temos tempo a perder."
            "Treinamos pelo resto da tarde."
            "Tentei ao máximo não cometer os mesmos erros e me adaptar a Juni."
            "Ao final de tudo, não acho que foi o suficiente pra mudar alguma coisa."
        "Conversar com Juni":
            m "Na verdade Juni..."
            m "Eu gostaria de conversar com você sobre uma coisa..."
            jn "A-Ah! Eu f-fiz algo de errado?"
            jn "É por causa dos meus erros? Eu ju-juro estou tentando melhorar!"
            m "Eu sei que você está realmente tentando..."
            m "Mas eu sinto que, por mais que tente, nada vai melhorar se você não tratar a causa."
            jn "..."
            m "E... Você sabe qual é a causa, não é?"
            jn "..."
            jn "Eu... Eu sei, sim. A minha insegurança..."
            jn "Só que... É muito difícil para mim."
            jn "Tudo em que consigo pensar é em como eu vou fracassar e-e aí todos vão rir de mim..."
            jn "N-Não sei como mudar isso... Eu já tentei de tudo."
            jn "Me desculpa, mesmo..."
            m "Hmm. Nós podemos começar com algo simples."
            m "Você pode mudar essa sua mentalidade..."
            jn "Co-como assim?"
            m "O pensamento é a base das nossa ações."
            m "Se você conseguir ser mais otimista a respeito de si mesma, já será um grande avanço."
            jn "É mesmo... ? Acho que não consigo..."
            m "consegue, sim! Eu acredito nisso."
            jn "Acredita... ?"
            m "Quer testar na prática? Vamos fazer a coreografia, mas dessa vez com mais calma."
            m "Não tem problema se alguma de nós acabar errando."
            jn "Ah... T-tudo bem."
            "Voltamos ao nosso treinamento."
            "Chegando na parte mais complicada da coreografia, Juni começa a se perder nos movimentos."
            jn "Ah, não..."
            "Mas ela consegue se recuperar antes do final."
            "E finalizamos muito bem a dança."
            jn "Me desculpa... E-Eu continuo errando..."
            m "Só que dessa vez você se recuperou."
            m "É um avanço!"
            jn "Mas-"
            m "Vamos continuar assim. Uma hora vai ficar perfeito."
            "Treinamos mais um pouco."
            "Até que Juni finalmente acerta o movimento."
            jn "V-Você viu? Eu consegui!"
            m "Eu vi!"
            m "E você está indo muito bem."
            jn "Ha! eu não acredito que eu finalmete consegui!"
            jn "Mas agora eu..."
            $ treino_juni = True

    jn "*suspiro* Estou exalsta..."
    m "Vamos encerrar o dia de hoje. Já fizemos mais do que o suficiente."

    if treino_juni:
        $ periodo = "Noite"
        $ atividade = "Antes de dormir"

        "Agora que estou no meu quarto, posso ver o que as pessoas estão dizendo na internet."
        "Encontrei uma notícia:"
        "'STAR'S SELECTION: reviravolta inesperada! Veja como as equipes do programa estão tendo um desempenho diferente do especulado.'"
        "'Interessante. Vou ver alguns trechos...'"
        "'... Ao contrário do que muitos pensaram, a equipe Linne-Nádia se mostra cada vez mais dinamica e sincronizada..."
        "'Superando as expectativas mais otimistas para as duas.'"
        "Então... Elas estão se dando bem? O que aconteceu?"
        "'Já a equipe Juni-Moonie está com um desempenho abaixo do esperado, embora haja muito esforço para mudar o cenário...'"
        "Pelo menos eles reconhecem..."
        "Oh, não... Isso é ruim."
        "Se continuar assim, eles vão me ver como uma fracassada e eu vou perder minha popularidade!"
        "Vou ver os comentários. Talvez isso me ajude um pouco..."
        "'???: Eu n queria falar nd, mas parece q a equipe j-m n confia em si mesma! Elas se sentem desconfortáveis estando uma perto da outra.'"
        "'???: Concordo. Tem algo de errado nisso, até pq não era pra ser assim... Achei q elas iria se dar tão bem.'"
        "Eu também achei..."
        "'???: Gnt, vcs não assistem o programa? É obvio q o desempenho caiu pq Juni erra por nervosismo.'"
        "'???: Tamb sofro com esse problema no dia a dia e echei muito legal q a moon tentou ajudar com isso.'"
        "'???: Nss sim! Só quem passa por isso sabe como é. Passei a ser fã delas por causa disso.'"
        "'???: Besteira! Não importa o motivo delas estarem se saindo mal. O que importa no final é o desempenho. E elas estão deixano muito a desejar.'"
        "'???: Acho q independe da situação, elas são obrigadas a performar da melhor forma possível. Afinal essa é a função delas."
        "As opiniões estão divididas... Ainda assim, existem apoiadores..."
        #"Aparentemente a minha popularidade não tá tão baixa."
        "Isso é reconfortante de certa forma."
        "Bem, Acho melhor eu ir dormir-"
        "Hã? Eu recebi uma mensagem?"
        "DO SR.STAR?!"
        "'Sr.Star: Boa noite, srta.Moonie.'"
        "'Sr.Star: Acredito que tenha visto as discussões a respeito do programa.'"
        "Meu Deus, eu vou levar um esporro!"
        "'Sr.Star: Mesmo em momentos difíceis, sua populariridade só sobe! Continue com o bom trabalho B).'"
        "Ah... No final era só isso."
        "Hmm. É bom saber que estou indo bem, apesar de tudo..."
        "Agora sim, posso dormir em paz."

label cap3_6:

    $ dia += 2
    $ periodo = "Manhã"
    $ atividade = "Treino de canto"

    ""    

    $ periodo = "Tarde"
    $ atividade = "Hora de almoço"

    "Na hora do almoço, noto que Juni pega apenas uma salada pequena para comer."
    "Sinto que ao decorrer desses dias de treinamento em duplas, ela passou a comer cada vez menos..."
    jn "Hm? O que foi?"

    menu(nvl=True):
        "...":
            m "Não é nada, não."
            jn "Tá bem..."
        "Está se alimentado direito?":
            m "Você anda comendo cada vez menos... Está se sentindo bem?"
            jn "Ah, i-isso..."
            jn "Não há nada de errado, é só q-que... Eu quero perder peso, sabe?"
            jn "Um dos meus shorts parou de servir..."

            menu(nvl=True):
                "Entendo.":
                    m "Entendo..."
                    jn "M-Mas não precisa se preocupar, t-tá?"
                    jn "Está t-tudo sob controle."
                "Pare de se preocupar com isso.":
                    m "Não tem problema nenhum ganhar peso..."
                    jn "N-Não tem problema?!"
                    jn "Mas é claro que tem! Todos a minha volta sempre me disseram isso!"
                    jn "E eles não nem um pouco gentis..."
                    m "..."
                    m "Caramba... Me desculpa. E-Eu não sabia..."
                    jn "..."
                    jn "Tá tudo bem. Não tinha como você saber..."
                    jn "E você só estava tentando ser legal, né?"
                    $ juni += 5   

    jn "..."
    jn "Acha... Acha que estamos progredindo?"
    m "Eu tenho certeza de que estamos!"
    jn "Sei..."
    jn "Não está dizendo isso só pra me animar, né?"
    "O que... ?"
    "Neste momento, Linne entra no refeitório."   
    ln "Olá, menimas!" 
    ln "Nossa, esses dias estão sendo tão corridos..."
    ln "Que nem consegui falar com vocês."
    "Ela se senta à mesa."
    ln "Então, como passaram esses dias?"
    jn "Passamos muito bem."
    ln "Ah, é mesmo? O seu rosto preocupado e cansado diz outra coisa..."
    jn "!!!"
    ln "Ha ha! Relaxa, eu só tava brincando!"
    jn "N-Não brinca com essas coisas..."
    m "E como está indo com a sua equipe, Linne?"
    ln "Eu? Bem... Não está sendo nada fácil."
    ln "Embora eu acredite estar fazendo um ótimo trabalho com a Nádia."
    ln "Manter uma pessoa agressiva e explosiva como ela calma é muuuuito cansativo."
    m "Agressiva... ?"
    ln "As vezes eu sinto até medo dela..."
    ln "E-Ela já chegou a me ameaçar algumas vezes."
    ln "E algumas coisas piores também..."
    "Algo pior? Será que..."
    ln "Vocês deveriam tomar cuidado com ela."
    ln "Delicadas e sensíveis do jeito que são, não iriam durar um minuto perto dela em um surto..."
    #"Ela está dizendo que... Ela foi agredida?! Nádia seria capaz?"
    ln "Apesar de tudo, está tudo indo bem melhor do que o esperado!"
    ln "Estou bem confiante para a apresentação de amanhã."
    # juni se sente ameacada
    jn "E-Está, é...?"
    jn "Err... Já acabou seu almoço Moon?"
    m "Já, sim. Por-"
    jn "Precisamos voltar ao treino. Agora."
    "Juni me puxa pelo braço até a saída."
    ln "Boa sorte no treino, meninas!"
    ln "Vocês vão precisar..."

    $ periodo = "Noite"
    $ atividade = "Treino da performance"

    "Ensaiamos a nossa performance várias vezes durante a tarde toda e o início da noite."
    m "Estamos indo bem!"
    m "Quer encerrar por hoj-"
    jn "N-Não! Ainda posso continuar!"
    m "Hã?"
    jn "A apresentação está proxima. Não dá pra ficar perdendo tempo!"
    m "É que... eu tô cansada-"
    jn "Ainda temos q-que melhorar..."
    m "O que tá acontecendo, Juni?"
    m "Você não é assim..."
    m "Anda agindo muito estranha ultimamente."
    jn "..."
    jn "Me-me desculpe..."
    jn "Podemos encerrar o treino."
    m "Tá bem..."
    "Ela deve estar muito estressada..."
    m "O que acha de tirar um descanço merecido agora de noite? Podemos sentar e jogar algum daqueles jogos da sala..."
    jn "Obrigada, mas estou sem muita vontade."
    jn "Eu vou deitar... Boa noite, Moon."
    "Ela se vira e se afasta apressadamente."
    "Bem... Eu tentei ajudar."

    $ atividade = "Antes de dormir"

    # ela ta no quato dela
    "Aff... Passar o dia treinando assim acabou comigo!"
    "Acredito que Juni também sente o mesmo... Só não quer conversar sobre."
    "Ela está se esforcando demais, no fim das contas..."
    "Quem sabe amanhã ela não vai estar melhor, né?"
    "Bem... Tô bem cansada e preciso dormir pra evitar olheiras. Mas acho que consigo ver como o programa rendeu hoje."
    "'???: Só eu que achei estranha a fala da Linne durante o almoço? Pq n tem ninguém falando sobre?'"
    "'???: Sempre q ela fala sobre o assunto, parece q ela tá sempre muito desconfortável.'"
    "'???: Essa história tá mt estranha... Deveriamos invertigar.'"
    "A maioria esmagadora dos comentários são voltados para a outra equipe..."
    "Será que isso atrapalha a minha popularidade?"
    # Moon ficou, inconscientemente, mais egoista e carente de atencao do publico (e uma viciada nos comentarios tmb)
    "A dinamica delas é interessante e tal... Mas, e eu?"
    "Eu também estou dando duro para ajudar a Juni! Ou eles já se esqueceram disso?"
    "... Quer saber? Acho que não tenho com o que me preocupar."
    "Amanhã é um novo dia e uma nova oportunidade de ganhar mais fãs!"
    "Vou arrasar na apresentação e todos ficaram encantados."

label cap3_7:

    $ dia += 1
    $ periodo = "???"
    $ atividade = "???"

    "... ? "
    "Acordo com um ruído vindo da cozinha."
    "Hmmm. São 3 da madrugada... O que pode ser?"
    "Me levanto para verificar."

    $ periodo = "Madrugada"

    "Chego á cozinha."
    jn "M-MOONIE?! O-O que faz acordada a essa hora?"
    m "Eu que te pergunto... Só acordei por causa de alguns barulhos vindos daqui."
    jn "É... Eu, b-bem..."
    "Observo diversas embalagens de comida espalhadas pela cozinha."
    m "Você... Comeu todo isso?"
    jn "N-Não..."
    jn "Sim! Eu não pude resistir!"
    jn "Todas aqui evoluiram tanto até agora."
    jn "Enquanto eu... Eu sempre volto a estaca 0."
    jn "Venho me sentindo tão... Incapaz! Um peso morto nas suas costas!"

    menu(nvl=True):
        "Você só deve estar cansada.":
            m "Ah, Juni... Está tarde e precisamos estar bem para nos apresentar."
            m "O cansaço deve estar mexendo com a sua cabeça. Não quer ir dormir, logo?"
            m "Garanto que se sentirá melhor depois de um descanço..."
            jn "Eu... Não consigo..."
            jn "..."

        "Está errada!":
            m "Isso não é verdade... Você evoluiu muito desde o começo."
            m "O seu esforço está dando resultados, acredite em mim!"
            jn "Pode ser verdade..."
            jn "Só que... Ainda não é o bastante!"
            jn "Não é o bastante para competir com Linne e Nádia!"
            jn "Não é o bastante para competir com você!"
            jn "E não é o bastante para o Sr.Star me respeitar minimamente!"
            jn "Ele ou qualquer outra pessoa..."
            jn "Sempre foi assim. Ninguém nunca me respeitou ou se lembrou de mim."
            jn "Faziam brincadeirinhas e me davam apelidos maldosos por causa do meu peso..."
            jn "Eles me julgavam por tudoo que fazia ou deixava de fazer. Mesmo quando emagreci com muito esforço não adiantou."
            jn "Cheguei a conclusão de que... P-Pode ser..."
            jn "O problema seja eu. Nunca fui capaz de me posicionar..."
            jn "Mesmo q-quando eu queria mudar..."

            menu(nvl=True):
                "Não é sua culpa":
                    m "Você não deve se culpar pela maldade dos outros..."
                    m "Tenho certeza que um dia vão se arrepender."
                    jn "Como pode ter tanta certeza?"
                    jn "Você... Não sabe como é passar por isso..."
                    jn "Bonita e gentil como é, nunca deve ter passado por nada parecido!"
                    jn "Todo mundo deve gostar de você, só por causa disso."
                    "Agora que ela falou..."
                    jn "Ser confiante fica bem mais fácil quando todos estão te apoiando..."
                    "..."
                
                "Você vai conseguir um dia":
                    m "Você tentou. E continua tentando..."
                    m "Não desista. Sempre sá pra melhorar."
                    m "Só porque você ainda não chegou onde queria, não significa que você é um fracasso."
                    jn "... Não é tão simples."

            jn "E-E eu sei que você está tentando ajudar, mas..."
            jn "..."
            m "*bocejo*"
            m "Podemos conversar mais tarde? Eu preciso muito dormir..."
        
    jn "T-Tudo bem... Eu vou voltar ao meu quarto."
    jn "Sintou muito por ter te acordado."
   
    $ periodo = "Tarde"
    $ atividade = "Antes da apresentação"

    "Está quase na hora da apresentação..."
    nn "E aí, Moon? Tudo pronto?"
    m "Err... Quase."
    m "Estou esperando a Juni terminar de se arrumar."
    nn "Tô ligada..."
    nn "E como ela tá? Ouvi vocês duas conversando na cozinha de madrugada."
    m "Não tenho certeza. Ela se esquivou de mim a manhã toda... Não consegui conversar com ela."
    "Escuto Linne gritar ao longe."
    ln "Vamos, Nádia. Não temos tempo pra ficar conversando!"
    "Nádia responde no mesmo tom."
    nn "Eu já vô!"
    nn "Vai ver se ela tá bem... Quem sabe ela precisa de uma força."
    ln "Anda logo!"
    nn "Eu falei que já tô indo!"
    nn "Grrr!, ela é um saco!"
    ln "Eu ouvi isso."
    nn "Era pra ouvir mesmo!"
    "Irritada, Nádia sai em direção ao palco."

    "Sobre o que Juni me contou ontem...."
    "Nunca pensei que a vida seria tão dura para uma pessoa tão doce."
    "E eu aqui... Me sentindo mal por não conquistar ainda mais a atenção do público..."
    "Caramba... Desde quando eu sou assim? Foi depois daquele trato?"
    "Oh, não..."
    "Melhor eu ir falar com Juni."

    # descricao do lugar
    m "Juni? Onde você tá?"
    jn "E-Estou aqui!"
    "Eu a encontro tentando fechar o ziper da roupa."
    jn "P-Pode me a-ajudar? Acho que... Que estou presa."
    "Ela diz isso quase sem ar."
    jn "Tá... Apertado..."
    m "Calma, deixa eu te ajudar."
    "Com um pouco de força, consigo fechar o ziper."
    m "Ufa! Aí está!"
    m "Como se sente?"
    jn "Não dá... Pra me mexer direito..."
    m "... Não quer vestir outra coisa?"
    jn "Não, não!"
    jn "Heh... Heh... A sensação de não servir mais uma roupa..."
    jn "É horrivel..."
    jn "Já se sentiu... A-Assim? Que não consegue caber em nada?"
    m "Acho que não."
    jn "É... Claro que não..."
    jn "Alguém com essa aparencia perfeita... Nunca entenderia..."

    menu(nvl=True):
        "Eu não sou perfeita":
            m "Na verdade, eu... Também tenho meus defeitos..."
            m "Eu não gosto muito da minha boca... Acho ela muito fina."
            m "E-E eu tenho um calo nesse meu dedo indicador..."
            jn "Ah, mas isso são detalhes muito pequenos. Ninguém liga pra isso."
            m "E eu..."
            m "Bem... Promete que não vai contar pra ningém?"
            jn "Hã? Ah, p-prometo!"
            m "Sabe, eu... Gostaria que..."
            m "Que minhas meus ceios fossem menores..."
            m "Algumas pessoas gostam de fazer alguns comentários... Que me deixam desconfortável..."
            jn "O-O que? É sério? Que... Que horror!"
            jn "Nossa, me... Me desculpa, mesmo!"
            jn "Nunca imaginei que... Você passou por isso..."
            jn "Eu... Eu me sinto uma idiota..."
            m "Não se sinta. Não é sua culpa."
            m "O ponto é que todo mundo tem algum defeito ou insegurança."
            jn "..."
            jn "É... Tem razão."
            jn "Nossa, Moon... Você é incrivel..."
            jn "Acho que você seria uma Idol maravilhosa. Todo mundo iria gostar de você!"
            jn "É sempre tão legal e compreensiva..."
            jn "E não precisa ficar fazendo joguinhos mentais e... Trapasseando como certa pessoa para ser querida."
            "Trapasseando..."
            jn "Você é... o que e-eu sempre quis ser..."
            jn "Inspiradora, bonita, gentil e honesta."
            "Honesta..."
            jn "Saiba que... Independente do que acontecer, eu estarei te apoaindo, viu?"
            m "..."
            m "Obrigada, Jun..."

            $ juni += 10
            $ confianca_juni = True

        "Está exagerando":
            m "Você tá sendo dramática."
            m "Olha, se continuar com esse pensamento, nunca vai conseguir melhorar."
            m "Vai ficar pra sempre se fazendo de vítima."
            jn "..."
            $ juni -= 5

    jn "Ah, olha a hora! Estamos atrasadas!"
    jn "T-Temos que... Ir agora..."
    "Ela continua com dificuldade de respirar."
    m "Não acha melhor trocar essa roupa?"
    jn "..."
    jn "É melhor."

    $ atividade = "Apresentação"

    "Corremos para chegar à área do palco."
    "Chegamos na metade da performance de Linne e Nádia."
    Srn "Onde estavam?! Por que demoraram tanto?"
    Srn "E que roupa é essa, srta.Juni?"
    jn "D-Desculpe! É que houve... Um imprevisto."
    m "O importante é que estamos aqui."
    "Dos bastidores, dá pra ver o final da performance das duas."
    "Elas realmente são muito talentosas..."
    jn "Será que temos alguma chance contra elas?"
    "Não."
    m "Claro. Vamos arrasar!"

    Srn "E essa foi a apresentação da primeira dupla!"
    Srn "Devo dizer que poucas performances me surpreendem como esta! Meus parabéns, meninas!"
    ln "Obrigada, Sr.Star."

    Srn "Agora, com vocês, a dupla Moonie-Juni! Apresentem-se, garotas!"
    ln "Boa apresentação, meninas."
    ln "Especiamente pra você, Juni."
    nn "Ah, cala a boca, Linne!"

    "Subimos ao palco e nos colocamos em posição antes da múscica começar."
    "Que sensação estranha..."

    "A música finalmente começa." 
    "Realizamos a apresentação conforme haviamos treinado."

    if confianca_juni:
        "Porém... Sinto algo de diferente."
        "Parece que, dessa vez, eu e Juni confiamos completamente uma na outra."

    "No final, acho que tudo ocorreu muito bem."

    Srn "Mas que performance adorável! Vocês estão de parabéns, também!"

    Srn "Agora, aguardaremos pelos resultados!"
    Srn "Mas não saiam daí! Estaremos de volta com muuuuito mais logo após os cemerciais!"

    ln "Meus parabéns, garotas. Vocês foram bem."
    ln "Como se sentem? Estão nervosas?"

    menu(nvl=True):
        "Sim.":
            m "Um pouquinho..."
            ln "Ah, mas isso é normal."
            ln "Vai aprender com o tempo que não dá pra ser a melhor em todas..."
            nn "*suspiro* Ela sabe disso. Todas nós sabemos."
            nn "Pare de bancar a expert em tudo."
            ln "Ei! Porque você tem que sempre tão grossa?"
            ln "Eu nem tava falando com você, Nádia..."

        "Não.":
            m "Nem um pouco."
            m "Acho que fomos ótimas."
            m "Não é, Jun?"
            jn "Sim, sim!"
            jn "Eu também estou muito feliz, apesar de tudo."
            ln "Ah, que legal..."

    $ periodo = "Noite"
    $ atividade = "Saída dos resultados"

    Srn "Estamos de volta, senhoras e senhores!"
    Srn "Chegou o momento mais esperado da noite..."
    Srn "O momento da eliminação!"
    Srn "Uma das nossa queridíssimas participantes terá que dar tchau ao reality."
    Srn "O que é uma pena ... Sempre me emociono nessas horas!"
    "É... Ele fica sempre muito animado com uma eliminação."
    Srn "Em instantes, aparecerá no telão a classificação das equipes."
    Srn "Lembrando que a equipe com a maior pontuação estará livre da eliminação!"
    Srn "E, logo após, aperecerá a pontuação individual de cada participante."
    Srn "A estrelinha que estiver na equipe com a menor média e tiver a menor pontuação..."
    Srn "Será eliiimiiinadaaaa!"
    Srn "Estão preparadas, garotas?"
    Srn "Porque aí... Vai!"
    "Os resultados aparecem do telão."
    Srn "Ora ora, mas que surpresa..."
    Srn "A equipe Linne-Nádia conseguiu a maior pontuação! Meus parabéns!"
    ln "Yey!"
    Srn "Quanto a equipe Moonie-Juni ficou em ultimo..."
    Srn "Significa que uma das duas, infelizmente, será eliminada!"
    "Não posso ser eliminada... Ou será que posso?"
    Srn "Agora, é a hora da verdade..."
    Srn "A eliminada da noite é..."
    "Nossas pontuações individuais aparecem na tela."
    Srn "Ora, mas que pena... A doce Juni é a nova desclassificada do programa!"
    jn "Oh..."
    Srn "Tem algo para dizer ao público, srta.Juni?"
    jn "Eu... Tenho sim."
    jn "Bem... Hãã..."
    jn "Fico muito triste de ter que deixar o reality."
    jn "M-Mas eu aprendi muito com a minha experiência no programa."
    jn "Muito mesmo!"
    jn "Eu gostaria de agradecer a todos vocês..."
    jn "Inclusive as outras participantes. Vocês são amigas maravilhosas, meninas!"
    jn "E agradecer ao Sr.Star pela oportunidade de estar aqui..."
    jn "E também por me deixar falar de vez em quando... "
    Srn "Não há de que, minha querda!"
    "Acho que ele não entedeu o que quis dizer."
    Srn "Isso era tudo?"
    jn "Hã... Creio que sim."
    Srn "Ótimo! Miuto obrigado pelas belas palavras, senhorita!"
    Srn "E assim, encerramos mais uma noite de eliminação!"
    Srn "Muuuuito obrigado por terem fica até aqui e desejo à todos uma ótima noite!"
    Srn "E até uma próxima!"
    Srn "Vocês estão dispensadas, queridas."

    jn "Bem... Acho que preciso ir."
    nn "Não sem se despedir da gente antes!"
    jn "Eu... Não gosto de despedida-"
    nn "Abraço coletivo!"
    "Nádia abraça Juni com força. Eu e Linne abraçamos em seguida."
    jn "Ah?! Ca-calma, pessoal!"
    nn "Cê foi ótima, Jun! Vou sentir sua falta."
    m "Isso mesmo. Tenha orgulho de você!"
    ln "Fez uma boa participação no programa no final das contas."
    jn "Ah... O-Obrigada..."
    jn "Vocês poderiam... Me soltar agora? Eu tô... Sufocada..."
    "Finalmemte soltamos Juni."
    jn "Ufa! Muito obrigada por tudo, gente..."
    jn "Err..."
    jn "Foi um prazer conhecer todas vocês."

    "Ela se vira e se afasta apressadamente."

    m "Tchau! O prazer foi todo meu..."
    "Ela virou o corredor e sumiu do nosso campo de visão."

    "Após isso, voltamos aos nossos dormitórios."

    jump cap4_1